// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1.3
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _topkernel_HH_
#define _topkernel_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "partitionandreduce0.h"
#include "topkernel_control_s_axi.h"
#include "topkernel_gmem0_m_axi.h"
#include "topkernel_gmem1_m_axi.h"
#include "topkernel_gmem2_m_axi.h"

namespace ap_rtl {

template<unsigned int C_M_AXI_GMEM0_ADDR_WIDTH = 32,
         unsigned int C_M_AXI_GMEM0_ID_WIDTH = 1,
         unsigned int C_M_AXI_GMEM0_AWUSER_WIDTH = 1,
         unsigned int C_M_AXI_GMEM0_DATA_WIDTH = 512,
         unsigned int C_M_AXI_GMEM0_WUSER_WIDTH = 1,
         unsigned int C_M_AXI_GMEM0_ARUSER_WIDTH = 1,
         unsigned int C_M_AXI_GMEM0_RUSER_WIDTH = 1,
         unsigned int C_M_AXI_GMEM0_BUSER_WIDTH = 1,
         unsigned int C_M_AXI_GMEM1_ADDR_WIDTH = 32,
         unsigned int C_M_AXI_GMEM1_ID_WIDTH = 1,
         unsigned int C_M_AXI_GMEM1_AWUSER_WIDTH = 1,
         unsigned int C_M_AXI_GMEM1_DATA_WIDTH = 512,
         unsigned int C_M_AXI_GMEM1_WUSER_WIDTH = 1,
         unsigned int C_M_AXI_GMEM1_ARUSER_WIDTH = 1,
         unsigned int C_M_AXI_GMEM1_RUSER_WIDTH = 1,
         unsigned int C_M_AXI_GMEM1_BUSER_WIDTH = 1,
         unsigned int C_M_AXI_GMEM2_ADDR_WIDTH = 32,
         unsigned int C_M_AXI_GMEM2_ID_WIDTH = 1,
         unsigned int C_M_AXI_GMEM2_AWUSER_WIDTH = 1,
         unsigned int C_M_AXI_GMEM2_DATA_WIDTH = 64,
         unsigned int C_M_AXI_GMEM2_WUSER_WIDTH = 1,
         unsigned int C_M_AXI_GMEM2_ARUSER_WIDTH = 1,
         unsigned int C_M_AXI_GMEM2_RUSER_WIDTH = 1,
         unsigned int C_M_AXI_GMEM2_BUSER_WIDTH = 1,
         unsigned int C_S_AXI_CONTROL_ADDR_WIDTH = 6,
         unsigned int C_S_AXI_CONTROL_DATA_WIDTH = 32>
struct topkernel : public sc_module {
    // Port declarations 155
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst_n;
    sc_out< sc_logic > m_axi_gmem0_AWVALID;
    sc_in< sc_logic > m_axi_gmem0_AWREADY;
    sc_out< sc_uint<C_M_AXI_GMEM0_ADDR_WIDTH> > m_axi_gmem0_AWADDR;
    sc_out< sc_uint<C_M_AXI_GMEM0_ID_WIDTH> > m_axi_gmem0_AWID;
    sc_out< sc_lv<8> > m_axi_gmem0_AWLEN;
    sc_out< sc_lv<3> > m_axi_gmem0_AWSIZE;
    sc_out< sc_lv<2> > m_axi_gmem0_AWBURST;
    sc_out< sc_lv<2> > m_axi_gmem0_AWLOCK;
    sc_out< sc_lv<4> > m_axi_gmem0_AWCACHE;
    sc_out< sc_lv<3> > m_axi_gmem0_AWPROT;
    sc_out< sc_lv<4> > m_axi_gmem0_AWQOS;
    sc_out< sc_lv<4> > m_axi_gmem0_AWREGION;
    sc_out< sc_uint<C_M_AXI_GMEM0_AWUSER_WIDTH> > m_axi_gmem0_AWUSER;
    sc_out< sc_logic > m_axi_gmem0_WVALID;
    sc_in< sc_logic > m_axi_gmem0_WREADY;
    sc_out< sc_uint<C_M_AXI_GMEM0_DATA_WIDTH> > m_axi_gmem0_WDATA;
    sc_out< sc_uint<C_M_AXI_GMEM0_DATA_WIDTH/8> > m_axi_gmem0_WSTRB;
    sc_out< sc_logic > m_axi_gmem0_WLAST;
    sc_out< sc_uint<C_M_AXI_GMEM0_ID_WIDTH> > m_axi_gmem0_WID;
    sc_out< sc_uint<C_M_AXI_GMEM0_WUSER_WIDTH> > m_axi_gmem0_WUSER;
    sc_out< sc_logic > m_axi_gmem0_ARVALID;
    sc_in< sc_logic > m_axi_gmem0_ARREADY;
    sc_out< sc_uint<C_M_AXI_GMEM0_ADDR_WIDTH> > m_axi_gmem0_ARADDR;
    sc_out< sc_uint<C_M_AXI_GMEM0_ID_WIDTH> > m_axi_gmem0_ARID;
    sc_out< sc_lv<8> > m_axi_gmem0_ARLEN;
    sc_out< sc_lv<3> > m_axi_gmem0_ARSIZE;
    sc_out< sc_lv<2> > m_axi_gmem0_ARBURST;
    sc_out< sc_lv<2> > m_axi_gmem0_ARLOCK;
    sc_out< sc_lv<4> > m_axi_gmem0_ARCACHE;
    sc_out< sc_lv<3> > m_axi_gmem0_ARPROT;
    sc_out< sc_lv<4> > m_axi_gmem0_ARQOS;
    sc_out< sc_lv<4> > m_axi_gmem0_ARREGION;
    sc_out< sc_uint<C_M_AXI_GMEM0_ARUSER_WIDTH> > m_axi_gmem0_ARUSER;
    sc_in< sc_logic > m_axi_gmem0_RVALID;
    sc_out< sc_logic > m_axi_gmem0_RREADY;
    sc_in< sc_uint<C_M_AXI_GMEM0_DATA_WIDTH> > m_axi_gmem0_RDATA;
    sc_in< sc_logic > m_axi_gmem0_RLAST;
    sc_in< sc_uint<C_M_AXI_GMEM0_ID_WIDTH> > m_axi_gmem0_RID;
    sc_in< sc_uint<C_M_AXI_GMEM0_RUSER_WIDTH> > m_axi_gmem0_RUSER;
    sc_in< sc_lv<2> > m_axi_gmem0_RRESP;
    sc_in< sc_logic > m_axi_gmem0_BVALID;
    sc_out< sc_logic > m_axi_gmem0_BREADY;
    sc_in< sc_lv<2> > m_axi_gmem0_BRESP;
    sc_in< sc_uint<C_M_AXI_GMEM0_ID_WIDTH> > m_axi_gmem0_BID;
    sc_in< sc_uint<C_M_AXI_GMEM0_BUSER_WIDTH> > m_axi_gmem0_BUSER;
    sc_out< sc_logic > m_axi_gmem1_AWVALID;
    sc_in< sc_logic > m_axi_gmem1_AWREADY;
    sc_out< sc_uint<C_M_AXI_GMEM1_ADDR_WIDTH> > m_axi_gmem1_AWADDR;
    sc_out< sc_uint<C_M_AXI_GMEM1_ID_WIDTH> > m_axi_gmem1_AWID;
    sc_out< sc_lv<8> > m_axi_gmem1_AWLEN;
    sc_out< sc_lv<3> > m_axi_gmem1_AWSIZE;
    sc_out< sc_lv<2> > m_axi_gmem1_AWBURST;
    sc_out< sc_lv<2> > m_axi_gmem1_AWLOCK;
    sc_out< sc_lv<4> > m_axi_gmem1_AWCACHE;
    sc_out< sc_lv<3> > m_axi_gmem1_AWPROT;
    sc_out< sc_lv<4> > m_axi_gmem1_AWQOS;
    sc_out< sc_lv<4> > m_axi_gmem1_AWREGION;
    sc_out< sc_uint<C_M_AXI_GMEM1_AWUSER_WIDTH> > m_axi_gmem1_AWUSER;
    sc_out< sc_logic > m_axi_gmem1_WVALID;
    sc_in< sc_logic > m_axi_gmem1_WREADY;
    sc_out< sc_uint<C_M_AXI_GMEM1_DATA_WIDTH> > m_axi_gmem1_WDATA;
    sc_out< sc_uint<C_M_AXI_GMEM1_DATA_WIDTH/8> > m_axi_gmem1_WSTRB;
    sc_out< sc_logic > m_axi_gmem1_WLAST;
    sc_out< sc_uint<C_M_AXI_GMEM1_ID_WIDTH> > m_axi_gmem1_WID;
    sc_out< sc_uint<C_M_AXI_GMEM1_WUSER_WIDTH> > m_axi_gmem1_WUSER;
    sc_out< sc_logic > m_axi_gmem1_ARVALID;
    sc_in< sc_logic > m_axi_gmem1_ARREADY;
    sc_out< sc_uint<C_M_AXI_GMEM1_ADDR_WIDTH> > m_axi_gmem1_ARADDR;
    sc_out< sc_uint<C_M_AXI_GMEM1_ID_WIDTH> > m_axi_gmem1_ARID;
    sc_out< sc_lv<8> > m_axi_gmem1_ARLEN;
    sc_out< sc_lv<3> > m_axi_gmem1_ARSIZE;
    sc_out< sc_lv<2> > m_axi_gmem1_ARBURST;
    sc_out< sc_lv<2> > m_axi_gmem1_ARLOCK;
    sc_out< sc_lv<4> > m_axi_gmem1_ARCACHE;
    sc_out< sc_lv<3> > m_axi_gmem1_ARPROT;
    sc_out< sc_lv<4> > m_axi_gmem1_ARQOS;
    sc_out< sc_lv<4> > m_axi_gmem1_ARREGION;
    sc_out< sc_uint<C_M_AXI_GMEM1_ARUSER_WIDTH> > m_axi_gmem1_ARUSER;
    sc_in< sc_logic > m_axi_gmem1_RVALID;
    sc_out< sc_logic > m_axi_gmem1_RREADY;
    sc_in< sc_uint<C_M_AXI_GMEM1_DATA_WIDTH> > m_axi_gmem1_RDATA;
    sc_in< sc_logic > m_axi_gmem1_RLAST;
    sc_in< sc_uint<C_M_AXI_GMEM1_ID_WIDTH> > m_axi_gmem1_RID;
    sc_in< sc_uint<C_M_AXI_GMEM1_RUSER_WIDTH> > m_axi_gmem1_RUSER;
    sc_in< sc_lv<2> > m_axi_gmem1_RRESP;
    sc_in< sc_logic > m_axi_gmem1_BVALID;
    sc_out< sc_logic > m_axi_gmem1_BREADY;
    sc_in< sc_lv<2> > m_axi_gmem1_BRESP;
    sc_in< sc_uint<C_M_AXI_GMEM1_ID_WIDTH> > m_axi_gmem1_BID;
    sc_in< sc_uint<C_M_AXI_GMEM1_BUSER_WIDTH> > m_axi_gmem1_BUSER;
    sc_out< sc_logic > m_axi_gmem2_AWVALID;
    sc_in< sc_logic > m_axi_gmem2_AWREADY;
    sc_out< sc_uint<C_M_AXI_GMEM2_ADDR_WIDTH> > m_axi_gmem2_AWADDR;
    sc_out< sc_uint<C_M_AXI_GMEM2_ID_WIDTH> > m_axi_gmem2_AWID;
    sc_out< sc_lv<8> > m_axi_gmem2_AWLEN;
    sc_out< sc_lv<3> > m_axi_gmem2_AWSIZE;
    sc_out< sc_lv<2> > m_axi_gmem2_AWBURST;
    sc_out< sc_lv<2> > m_axi_gmem2_AWLOCK;
    sc_out< sc_lv<4> > m_axi_gmem2_AWCACHE;
    sc_out< sc_lv<3> > m_axi_gmem2_AWPROT;
    sc_out< sc_lv<4> > m_axi_gmem2_AWQOS;
    sc_out< sc_lv<4> > m_axi_gmem2_AWREGION;
    sc_out< sc_uint<C_M_AXI_GMEM2_AWUSER_WIDTH> > m_axi_gmem2_AWUSER;
    sc_out< sc_logic > m_axi_gmem2_WVALID;
    sc_in< sc_logic > m_axi_gmem2_WREADY;
    sc_out< sc_uint<C_M_AXI_GMEM2_DATA_WIDTH> > m_axi_gmem2_WDATA;
    sc_out< sc_uint<C_M_AXI_GMEM2_DATA_WIDTH/8> > m_axi_gmem2_WSTRB;
    sc_out< sc_logic > m_axi_gmem2_WLAST;
    sc_out< sc_uint<C_M_AXI_GMEM2_ID_WIDTH> > m_axi_gmem2_WID;
    sc_out< sc_uint<C_M_AXI_GMEM2_WUSER_WIDTH> > m_axi_gmem2_WUSER;
    sc_out< sc_logic > m_axi_gmem2_ARVALID;
    sc_in< sc_logic > m_axi_gmem2_ARREADY;
    sc_out< sc_uint<C_M_AXI_GMEM2_ADDR_WIDTH> > m_axi_gmem2_ARADDR;
    sc_out< sc_uint<C_M_AXI_GMEM2_ID_WIDTH> > m_axi_gmem2_ARID;
    sc_out< sc_lv<8> > m_axi_gmem2_ARLEN;
    sc_out< sc_lv<3> > m_axi_gmem2_ARSIZE;
    sc_out< sc_lv<2> > m_axi_gmem2_ARBURST;
    sc_out< sc_lv<2> > m_axi_gmem2_ARLOCK;
    sc_out< sc_lv<4> > m_axi_gmem2_ARCACHE;
    sc_out< sc_lv<3> > m_axi_gmem2_ARPROT;
    sc_out< sc_lv<4> > m_axi_gmem2_ARQOS;
    sc_out< sc_lv<4> > m_axi_gmem2_ARREGION;
    sc_out< sc_uint<C_M_AXI_GMEM2_ARUSER_WIDTH> > m_axi_gmem2_ARUSER;
    sc_in< sc_logic > m_axi_gmem2_RVALID;
    sc_out< sc_logic > m_axi_gmem2_RREADY;
    sc_in< sc_uint<C_M_AXI_GMEM2_DATA_WIDTH> > m_axi_gmem2_RDATA;
    sc_in< sc_logic > m_axi_gmem2_RLAST;
    sc_in< sc_uint<C_M_AXI_GMEM2_ID_WIDTH> > m_axi_gmem2_RID;
    sc_in< sc_uint<C_M_AXI_GMEM2_RUSER_WIDTH> > m_axi_gmem2_RUSER;
    sc_in< sc_lv<2> > m_axi_gmem2_RRESP;
    sc_in< sc_logic > m_axi_gmem2_BVALID;
    sc_out< sc_logic > m_axi_gmem2_BREADY;
    sc_in< sc_lv<2> > m_axi_gmem2_BRESP;
    sc_in< sc_uint<C_M_AXI_GMEM2_ID_WIDTH> > m_axi_gmem2_BID;
    sc_in< sc_uint<C_M_AXI_GMEM2_BUSER_WIDTH> > m_axi_gmem2_BUSER;
    sc_in< sc_logic > s_axi_control_AWVALID;
    sc_out< sc_logic > s_axi_control_AWREADY;
    sc_in< sc_uint<C_S_AXI_CONTROL_ADDR_WIDTH> > s_axi_control_AWADDR;
    sc_in< sc_logic > s_axi_control_WVALID;
    sc_out< sc_logic > s_axi_control_WREADY;
    sc_in< sc_uint<C_S_AXI_CONTROL_DATA_WIDTH> > s_axi_control_WDATA;
    sc_in< sc_uint<C_S_AXI_CONTROL_DATA_WIDTH/8> > s_axi_control_WSTRB;
    sc_in< sc_logic > s_axi_control_ARVALID;
    sc_out< sc_logic > s_axi_control_ARREADY;
    sc_in< sc_uint<C_S_AXI_CONTROL_ADDR_WIDTH> > s_axi_control_ARADDR;
    sc_out< sc_logic > s_axi_control_RVALID;
    sc_in< sc_logic > s_axi_control_RREADY;
    sc_out< sc_uint<C_S_AXI_CONTROL_DATA_WIDTH> > s_axi_control_RDATA;
    sc_out< sc_lv<2> > s_axi_control_RRESP;
    sc_out< sc_logic > s_axi_control_BVALID;
    sc_in< sc_logic > s_axi_control_BREADY;
    sc_out< sc_lv<2> > s_axi_control_BRESP;
    sc_out< sc_logic > interrupt;
    sc_signal< sc_logic > ap_var_for_const0;


    // Module declarations
    topkernel(sc_module_name name);
    SC_HAS_PROCESS(topkernel);

    ~topkernel();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    topkernel_control_s_axi<C_S_AXI_CONTROL_ADDR_WIDTH,C_S_AXI_CONTROL_DATA_WIDTH>* topkernel_control_s_axi_U;
    topkernel_gmem0_m_axi<0,512,32,5,16,16,64,64,C_M_AXI_GMEM0_ID_WIDTH,C_M_AXI_GMEM0_ADDR_WIDTH,C_M_AXI_GMEM0_DATA_WIDTH,C_M_AXI_GMEM0_AWUSER_WIDTH,C_M_AXI_GMEM0_ARUSER_WIDTH,C_M_AXI_GMEM0_WUSER_WIDTH,C_M_AXI_GMEM0_RUSER_WIDTH,C_M_AXI_GMEM0_BUSER_WIDTH,C_M_AXI_GMEM0_USER_VALUE,C_M_AXI_GMEM0_PROT_VALUE,C_M_AXI_GMEM0_CACHE_VALUE>* topkernel_gmem0_m_axi_U;
    topkernel_gmem1_m_axi<0,512,32,5,16,16,64,64,C_M_AXI_GMEM1_ID_WIDTH,C_M_AXI_GMEM1_ADDR_WIDTH,C_M_AXI_GMEM1_DATA_WIDTH,C_M_AXI_GMEM1_AWUSER_WIDTH,C_M_AXI_GMEM1_ARUSER_WIDTH,C_M_AXI_GMEM1_WUSER_WIDTH,C_M_AXI_GMEM1_RUSER_WIDTH,C_M_AXI_GMEM1_BUSER_WIDTH,C_M_AXI_GMEM1_USER_VALUE,C_M_AXI_GMEM1_PROT_VALUE,C_M_AXI_GMEM1_CACHE_VALUE>* topkernel_gmem1_m_axi_U;
    topkernel_gmem2_m_axi<0,64,32,5,16,16,16,16,C_M_AXI_GMEM2_ID_WIDTH,C_M_AXI_GMEM2_ADDR_WIDTH,C_M_AXI_GMEM2_DATA_WIDTH,C_M_AXI_GMEM2_AWUSER_WIDTH,C_M_AXI_GMEM2_ARUSER_WIDTH,C_M_AXI_GMEM2_WUSER_WIDTH,C_M_AXI_GMEM2_RUSER_WIDTH,C_M_AXI_GMEM2_BUSER_WIDTH,C_M_AXI_GMEM2_USER_VALUE,C_M_AXI_GMEM2_PROT_VALUE,C_M_AXI_GMEM2_CACHE_VALUE>* topkernel_gmem2_m_axi_U;
    partitionandreduce0* grp_partitionandreduce0_fu_178;
    sc_signal< sc_logic > ap_rst_n_inv;
    sc_signal< sc_logic > ap_start;
    sc_signal< sc_logic > ap_done;
    sc_signal< sc_logic > ap_idle;
    sc_signal< sc_lv<17> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_logic > ap_ready;
    sc_signal< sc_lv<32> > kvsourcedramA_V;
    sc_signal< sc_lv<32> > kvdestdramA_V;
    sc_signal< sc_lv<32> > kvstatsA;
    sc_signal< sc_logic > gmem2_blk_n_AR;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_logic > gmem2_blk_n_R;
    sc_signal< sc_logic > ap_CS_fsm_state9;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_logic > ap_CS_fsm_state10;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_logic > ap_CS_fsm_state11;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_logic > ap_CS_fsm_state12;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_logic > ap_CS_fsm_state13;
    sc_signal< sc_logic > ap_CS_fsm_state7;
    sc_signal< sc_logic > ap_CS_fsm_state14;
    sc_signal< sc_logic > ap_CS_fsm_state8;
    sc_signal< sc_logic > ap_CS_fsm_state15;
    sc_signal< sc_logic > gmem0_AWVALID;
    sc_signal< sc_logic > gmem0_AWREADY;
    sc_signal< sc_logic > gmem0_WVALID;
    sc_signal< sc_logic > gmem0_WREADY;
    sc_signal< sc_logic > gmem0_ARVALID;
    sc_signal< sc_logic > gmem0_ARREADY;
    sc_signal< sc_logic > gmem0_RVALID;
    sc_signal< sc_logic > gmem0_RREADY;
    sc_signal< sc_lv<512> > gmem0_RDATA;
    sc_signal< sc_logic > gmem0_RLAST;
    sc_signal< sc_lv<1> > gmem0_RID;
    sc_signal< sc_lv<1> > gmem0_RUSER;
    sc_signal< sc_lv<2> > gmem0_RRESP;
    sc_signal< sc_logic > gmem0_BVALID;
    sc_signal< sc_logic > gmem0_BREADY;
    sc_signal< sc_lv<2> > gmem0_BRESP;
    sc_signal< sc_lv<1> > gmem0_BID;
    sc_signal< sc_lv<1> > gmem0_BUSER;
    sc_signal< sc_logic > gmem1_AWVALID;
    sc_signal< sc_logic > gmem1_AWREADY;
    sc_signal< sc_logic > gmem1_WVALID;
    sc_signal< sc_logic > gmem1_WREADY;
    sc_signal< sc_logic > gmem1_ARVALID;
    sc_signal< sc_logic > gmem1_ARREADY;
    sc_signal< sc_logic > gmem1_RVALID;
    sc_signal< sc_logic > gmem1_RREADY;
    sc_signal< sc_lv<512> > gmem1_RDATA;
    sc_signal< sc_logic > gmem1_RLAST;
    sc_signal< sc_lv<1> > gmem1_RID;
    sc_signal< sc_lv<1> > gmem1_RUSER;
    sc_signal< sc_lv<2> > gmem1_RRESP;
    sc_signal< sc_logic > gmem1_BVALID;
    sc_signal< sc_logic > gmem1_BREADY;
    sc_signal< sc_lv<2> > gmem1_BRESP;
    sc_signal< sc_lv<1> > gmem1_BID;
    sc_signal< sc_lv<1> > gmem1_BUSER;
    sc_signal< sc_logic > gmem2_AWVALID;
    sc_signal< sc_logic > gmem2_AWREADY;
    sc_signal< sc_logic > gmem2_WVALID;
    sc_signal< sc_logic > gmem2_WREADY;
    sc_signal< sc_logic > gmem2_ARVALID;
    sc_signal< sc_logic > gmem2_ARREADY;
    sc_signal< sc_lv<32> > gmem2_ARADDR;
    sc_signal< sc_lv<1> > gmem2_ARID;
    sc_signal< sc_lv<32> > gmem2_ARLEN;
    sc_signal< sc_lv<3> > gmem2_ARSIZE;
    sc_signal< sc_lv<2> > gmem2_ARBURST;
    sc_signal< sc_lv<2> > gmem2_ARLOCK;
    sc_signal< sc_lv<4> > gmem2_ARCACHE;
    sc_signal< sc_lv<3> > gmem2_ARPROT;
    sc_signal< sc_lv<4> > gmem2_ARQOS;
    sc_signal< sc_lv<4> > gmem2_ARREGION;
    sc_signal< sc_lv<1> > gmem2_ARUSER;
    sc_signal< sc_logic > gmem2_RVALID;
    sc_signal< sc_logic > gmem2_RREADY;
    sc_signal< sc_lv<64> > gmem2_RDATA;
    sc_signal< sc_logic > gmem2_RLAST;
    sc_signal< sc_lv<1> > gmem2_RID;
    sc_signal< sc_lv<1> > gmem2_RUSER;
    sc_signal< sc_lv<2> > gmem2_RRESP;
    sc_signal< sc_logic > gmem2_BVALID;
    sc_signal< sc_logic > gmem2_BREADY;
    sc_signal< sc_lv<2> > gmem2_BRESP;
    sc_signal< sc_lv<1> > gmem2_BID;
    sc_signal< sc_lv<1> > gmem2_BUSER;
    sc_signal< sc_lv<29> > kvstatsA5_fu_198_p4;
    sc_signal< sc_lv<29> > kvstatsA5_reg_366;
    sc_signal< sc_lv<30> > p_cast_fu_208_p1;
    sc_signal< sc_lv<30> > p_cast_reg_371;
    sc_signal< sc_lv<26> > kvdestdramA_V3_reg_381;
    sc_signal< sc_lv<26> > kvsourcedramA_V1_reg_386;
    sc_signal< sc_lv<30> > add_ln3244_fu_232_p2;
    sc_signal< sc_lv<30> > add_ln3244_reg_391;
    sc_signal< sc_lv<30> > add_ln3247_fu_248_p2;
    sc_signal< sc_lv<30> > add_ln3247_reg_402;
    sc_signal< sc_lv<30> > add_ln3248_fu_263_p2;
    sc_signal< sc_lv<30> > add_ln3248_reg_413;
    sc_signal< sc_lv<30> > add_ln3249_fu_278_p2;
    sc_signal< sc_lv<30> > add_ln3249_reg_424;
    sc_signal< sc_lv<30> > add_ln3251_fu_293_p2;
    sc_signal< sc_lv<30> > add_ln3251_reg_435;
    sc_signal< sc_lv<30> > add_ln3255_fu_308_p2;
    sc_signal< sc_lv<30> > add_ln3255_reg_446;
    sc_signal< sc_lv<30> > add_ln3257_fu_323_p2;
    sc_signal< sc_lv<30> > add_ln3257_reg_457;
    sc_signal< sc_lv<32> > globalparams_runkern_fu_338_p1;
    sc_signal< sc_lv<32> > globalparams_runkern_reg_468;
    sc_signal< sc_lv<32> > globalparams_partiti_fu_342_p1;
    sc_signal< sc_lv<32> > globalparams_partiti_reg_473;
    sc_signal< sc_lv<32> > globalparams_reducec_fu_346_p1;
    sc_signal< sc_lv<32> > globalparams_reducec_reg_478;
    sc_signal< sc_lv<32> > globalparams_vbegin_fu_350_p1;
    sc_signal< sc_lv<32> > globalparams_vbegin_reg_483;
    sc_signal< sc_lv<32> > globalparams_treedep_fu_354_p1;
    sc_signal< sc_lv<32> > globalparams_treedep_reg_488;
    sc_signal< sc_lv<32> > globalparams_runsize_fu_358_p1;
    sc_signal< sc_lv<32> > globalparams_runsize_reg_493;
    sc_signal< sc_lv<32> > globalparams_statsal_fu_362_p1;
    sc_signal< sc_lv<32> > globalparams_statsal_reg_498;
    sc_signal< sc_logic > grp_partitionandreduce0_fu_178_ap_start;
    sc_signal< sc_logic > grp_partitionandreduce0_fu_178_ap_done;
    sc_signal< sc_logic > grp_partitionandreduce0_fu_178_ap_idle;
    sc_signal< sc_logic > grp_partitionandreduce0_fu_178_ap_ready;
    sc_signal< sc_logic > grp_partitionandreduce0_fu_178_m_axi_kvsourcedram_V_AWVALID;
    sc_signal< sc_lv<32> > grp_partitionandreduce0_fu_178_m_axi_kvsourcedram_V_AWADDR;
    sc_signal< sc_lv<1> > grp_partitionandreduce0_fu_178_m_axi_kvsourcedram_V_AWID;
    sc_signal< sc_lv<32> > grp_partitionandreduce0_fu_178_m_axi_kvsourcedram_V_AWLEN;
    sc_signal< sc_lv<3> > grp_partitionandreduce0_fu_178_m_axi_kvsourcedram_V_AWSIZE;
    sc_signal< sc_lv<2> > grp_partitionandreduce0_fu_178_m_axi_kvsourcedram_V_AWBURST;
    sc_signal< sc_lv<2> > grp_partitionandreduce0_fu_178_m_axi_kvsourcedram_V_AWLOCK;
    sc_signal< sc_lv<4> > grp_partitionandreduce0_fu_178_m_axi_kvsourcedram_V_AWCACHE;
    sc_signal< sc_lv<3> > grp_partitionandreduce0_fu_178_m_axi_kvsourcedram_V_AWPROT;
    sc_signal< sc_lv<4> > grp_partitionandreduce0_fu_178_m_axi_kvsourcedram_V_AWQOS;
    sc_signal< sc_lv<4> > grp_partitionandreduce0_fu_178_m_axi_kvsourcedram_V_AWREGION;
    sc_signal< sc_lv<1> > grp_partitionandreduce0_fu_178_m_axi_kvsourcedram_V_AWUSER;
    sc_signal< sc_logic > grp_partitionandreduce0_fu_178_m_axi_kvsourcedram_V_WVALID;
    sc_signal< sc_lv<512> > grp_partitionandreduce0_fu_178_m_axi_kvsourcedram_V_WDATA;
    sc_signal< sc_lv<64> > grp_partitionandreduce0_fu_178_m_axi_kvsourcedram_V_WSTRB;
    sc_signal< sc_logic > grp_partitionandreduce0_fu_178_m_axi_kvsourcedram_V_WLAST;
    sc_signal< sc_lv<1> > grp_partitionandreduce0_fu_178_m_axi_kvsourcedram_V_WID;
    sc_signal< sc_lv<1> > grp_partitionandreduce0_fu_178_m_axi_kvsourcedram_V_WUSER;
    sc_signal< sc_logic > grp_partitionandreduce0_fu_178_m_axi_kvsourcedram_V_ARVALID;
    sc_signal< sc_lv<32> > grp_partitionandreduce0_fu_178_m_axi_kvsourcedram_V_ARADDR;
    sc_signal< sc_lv<1> > grp_partitionandreduce0_fu_178_m_axi_kvsourcedram_V_ARID;
    sc_signal< sc_lv<32> > grp_partitionandreduce0_fu_178_m_axi_kvsourcedram_V_ARLEN;
    sc_signal< sc_lv<3> > grp_partitionandreduce0_fu_178_m_axi_kvsourcedram_V_ARSIZE;
    sc_signal< sc_lv<2> > grp_partitionandreduce0_fu_178_m_axi_kvsourcedram_V_ARBURST;
    sc_signal< sc_lv<2> > grp_partitionandreduce0_fu_178_m_axi_kvsourcedram_V_ARLOCK;
    sc_signal< sc_lv<4> > grp_partitionandreduce0_fu_178_m_axi_kvsourcedram_V_ARCACHE;
    sc_signal< sc_lv<3> > grp_partitionandreduce0_fu_178_m_axi_kvsourcedram_V_ARPROT;
    sc_signal< sc_lv<4> > grp_partitionandreduce0_fu_178_m_axi_kvsourcedram_V_ARQOS;
    sc_signal< sc_lv<4> > grp_partitionandreduce0_fu_178_m_axi_kvsourcedram_V_ARREGION;
    sc_signal< sc_lv<1> > grp_partitionandreduce0_fu_178_m_axi_kvsourcedram_V_ARUSER;
    sc_signal< sc_logic > grp_partitionandreduce0_fu_178_m_axi_kvsourcedram_V_RREADY;
    sc_signal< sc_logic > grp_partitionandreduce0_fu_178_m_axi_kvsourcedram_V_BREADY;
    sc_signal< sc_logic > grp_partitionandreduce0_fu_178_m_axi_kvdestdram_V_AWVALID;
    sc_signal< sc_lv<32> > grp_partitionandreduce0_fu_178_m_axi_kvdestdram_V_AWADDR;
    sc_signal< sc_lv<1> > grp_partitionandreduce0_fu_178_m_axi_kvdestdram_V_AWID;
    sc_signal< sc_lv<32> > grp_partitionandreduce0_fu_178_m_axi_kvdestdram_V_AWLEN;
    sc_signal< sc_lv<3> > grp_partitionandreduce0_fu_178_m_axi_kvdestdram_V_AWSIZE;
    sc_signal< sc_lv<2> > grp_partitionandreduce0_fu_178_m_axi_kvdestdram_V_AWBURST;
    sc_signal< sc_lv<2> > grp_partitionandreduce0_fu_178_m_axi_kvdestdram_V_AWLOCK;
    sc_signal< sc_lv<4> > grp_partitionandreduce0_fu_178_m_axi_kvdestdram_V_AWCACHE;
    sc_signal< sc_lv<3> > grp_partitionandreduce0_fu_178_m_axi_kvdestdram_V_AWPROT;
    sc_signal< sc_lv<4> > grp_partitionandreduce0_fu_178_m_axi_kvdestdram_V_AWQOS;
    sc_signal< sc_lv<4> > grp_partitionandreduce0_fu_178_m_axi_kvdestdram_V_AWREGION;
    sc_signal< sc_lv<1> > grp_partitionandreduce0_fu_178_m_axi_kvdestdram_V_AWUSER;
    sc_signal< sc_logic > grp_partitionandreduce0_fu_178_m_axi_kvdestdram_V_WVALID;
    sc_signal< sc_lv<512> > grp_partitionandreduce0_fu_178_m_axi_kvdestdram_V_WDATA;
    sc_signal< sc_lv<64> > grp_partitionandreduce0_fu_178_m_axi_kvdestdram_V_WSTRB;
    sc_signal< sc_logic > grp_partitionandreduce0_fu_178_m_axi_kvdestdram_V_WLAST;
    sc_signal< sc_lv<1> > grp_partitionandreduce0_fu_178_m_axi_kvdestdram_V_WID;
    sc_signal< sc_lv<1> > grp_partitionandreduce0_fu_178_m_axi_kvdestdram_V_WUSER;
    sc_signal< sc_logic > grp_partitionandreduce0_fu_178_m_axi_kvdestdram_V_ARVALID;
    sc_signal< sc_lv<32> > grp_partitionandreduce0_fu_178_m_axi_kvdestdram_V_ARADDR;
    sc_signal< sc_lv<1> > grp_partitionandreduce0_fu_178_m_axi_kvdestdram_V_ARID;
    sc_signal< sc_lv<32> > grp_partitionandreduce0_fu_178_m_axi_kvdestdram_V_ARLEN;
    sc_signal< sc_lv<3> > grp_partitionandreduce0_fu_178_m_axi_kvdestdram_V_ARSIZE;
    sc_signal< sc_lv<2> > grp_partitionandreduce0_fu_178_m_axi_kvdestdram_V_ARBURST;
    sc_signal< sc_lv<2> > grp_partitionandreduce0_fu_178_m_axi_kvdestdram_V_ARLOCK;
    sc_signal< sc_lv<4> > grp_partitionandreduce0_fu_178_m_axi_kvdestdram_V_ARCACHE;
    sc_signal< sc_lv<3> > grp_partitionandreduce0_fu_178_m_axi_kvdestdram_V_ARPROT;
    sc_signal< sc_lv<4> > grp_partitionandreduce0_fu_178_m_axi_kvdestdram_V_ARQOS;
    sc_signal< sc_lv<4> > grp_partitionandreduce0_fu_178_m_axi_kvdestdram_V_ARREGION;
    sc_signal< sc_lv<1> > grp_partitionandreduce0_fu_178_m_axi_kvdestdram_V_ARUSER;
    sc_signal< sc_logic > grp_partitionandreduce0_fu_178_m_axi_kvdestdram_V_RREADY;
    sc_signal< sc_logic > grp_partitionandreduce0_fu_178_m_axi_kvdestdram_V_BREADY;
    sc_signal< sc_logic > grp_partitionandreduce0_fu_178_m_axi_kvstats_AWVALID;
    sc_signal< sc_lv<32> > grp_partitionandreduce0_fu_178_m_axi_kvstats_AWADDR;
    sc_signal< sc_lv<1> > grp_partitionandreduce0_fu_178_m_axi_kvstats_AWID;
    sc_signal< sc_lv<32> > grp_partitionandreduce0_fu_178_m_axi_kvstats_AWLEN;
    sc_signal< sc_lv<3> > grp_partitionandreduce0_fu_178_m_axi_kvstats_AWSIZE;
    sc_signal< sc_lv<2> > grp_partitionandreduce0_fu_178_m_axi_kvstats_AWBURST;
    sc_signal< sc_lv<2> > grp_partitionandreduce0_fu_178_m_axi_kvstats_AWLOCK;
    sc_signal< sc_lv<4> > grp_partitionandreduce0_fu_178_m_axi_kvstats_AWCACHE;
    sc_signal< sc_lv<3> > grp_partitionandreduce0_fu_178_m_axi_kvstats_AWPROT;
    sc_signal< sc_lv<4> > grp_partitionandreduce0_fu_178_m_axi_kvstats_AWQOS;
    sc_signal< sc_lv<4> > grp_partitionandreduce0_fu_178_m_axi_kvstats_AWREGION;
    sc_signal< sc_lv<1> > grp_partitionandreduce0_fu_178_m_axi_kvstats_AWUSER;
    sc_signal< sc_logic > grp_partitionandreduce0_fu_178_m_axi_kvstats_WVALID;
    sc_signal< sc_lv<64> > grp_partitionandreduce0_fu_178_m_axi_kvstats_WDATA;
    sc_signal< sc_lv<8> > grp_partitionandreduce0_fu_178_m_axi_kvstats_WSTRB;
    sc_signal< sc_logic > grp_partitionandreduce0_fu_178_m_axi_kvstats_WLAST;
    sc_signal< sc_lv<1> > grp_partitionandreduce0_fu_178_m_axi_kvstats_WID;
    sc_signal< sc_lv<1> > grp_partitionandreduce0_fu_178_m_axi_kvstats_WUSER;
    sc_signal< sc_logic > grp_partitionandreduce0_fu_178_m_axi_kvstats_ARVALID;
    sc_signal< sc_lv<32> > grp_partitionandreduce0_fu_178_m_axi_kvstats_ARADDR;
    sc_signal< sc_lv<1> > grp_partitionandreduce0_fu_178_m_axi_kvstats_ARID;
    sc_signal< sc_lv<32> > grp_partitionandreduce0_fu_178_m_axi_kvstats_ARLEN;
    sc_signal< sc_lv<3> > grp_partitionandreduce0_fu_178_m_axi_kvstats_ARSIZE;
    sc_signal< sc_lv<2> > grp_partitionandreduce0_fu_178_m_axi_kvstats_ARBURST;
    sc_signal< sc_lv<2> > grp_partitionandreduce0_fu_178_m_axi_kvstats_ARLOCK;
    sc_signal< sc_lv<4> > grp_partitionandreduce0_fu_178_m_axi_kvstats_ARCACHE;
    sc_signal< sc_lv<3> > grp_partitionandreduce0_fu_178_m_axi_kvstats_ARPROT;
    sc_signal< sc_lv<4> > grp_partitionandreduce0_fu_178_m_axi_kvstats_ARQOS;
    sc_signal< sc_lv<4> > grp_partitionandreduce0_fu_178_m_axi_kvstats_ARREGION;
    sc_signal< sc_lv<1> > grp_partitionandreduce0_fu_178_m_axi_kvstats_ARUSER;
    sc_signal< sc_logic > grp_partitionandreduce0_fu_178_m_axi_kvstats_RREADY;
    sc_signal< sc_logic > grp_partitionandreduce0_fu_178_m_axi_kvstats_BREADY;
    sc_signal< sc_logic > grp_partitionandreduce0_fu_178_ap_start_reg;
    sc_signal< sc_logic > ap_CS_fsm_state16;
    sc_signal< sc_logic > ap_CS_fsm_state17;
    sc_signal< sc_lv<64> > zext_ln3244_fu_238_p1;
    sc_signal< sc_lv<64> > zext_ln3247_fu_253_p1;
    sc_signal< sc_lv<64> > zext_ln3248_fu_268_p1;
    sc_signal< sc_lv<64> > zext_ln3249_fu_283_p1;
    sc_signal< sc_lv<64> > zext_ln3251_fu_298_p1;
    sc_signal< sc_lv<64> > zext_ln3255_fu_313_p1;
    sc_signal< sc_lv<64> > zext_ln3257_fu_328_p1;
    sc_signal< sc_lv<17> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<17> ap_ST_fsm_state1;
    static const sc_lv<17> ap_ST_fsm_state2;
    static const sc_lv<17> ap_ST_fsm_state3;
    static const sc_lv<17> ap_ST_fsm_state4;
    static const sc_lv<17> ap_ST_fsm_state5;
    static const sc_lv<17> ap_ST_fsm_state6;
    static const sc_lv<17> ap_ST_fsm_state7;
    static const sc_lv<17> ap_ST_fsm_state8;
    static const sc_lv<17> ap_ST_fsm_state9;
    static const sc_lv<17> ap_ST_fsm_state10;
    static const sc_lv<17> ap_ST_fsm_state11;
    static const sc_lv<17> ap_ST_fsm_state12;
    static const sc_lv<17> ap_ST_fsm_state13;
    static const sc_lv<17> ap_ST_fsm_state14;
    static const sc_lv<17> ap_ST_fsm_state15;
    static const sc_lv<17> ap_ST_fsm_state16;
    static const sc_lv<17> ap_ST_fsm_state17;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_C;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_D;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<32> ap_const_lv32_E;
    static const int C_S_AXI_DATA_WIDTH;
    static const int C_M_AXI_GMEM0_USER_VALUE;
    static const int C_M_AXI_GMEM0_PROT_VALUE;
    static const int C_M_AXI_GMEM0_CACHE_VALUE;
    static const int C_M_AXI_DATA_WIDTH;
    static const int C_M_AXI_GMEM1_USER_VALUE;
    static const int C_M_AXI_GMEM1_PROT_VALUE;
    static const int C_M_AXI_GMEM1_CACHE_VALUE;
    static const int C_M_AXI_GMEM2_USER_VALUE;
    static const int C_M_AXI_GMEM2_PROT_VALUE;
    static const int C_M_AXI_GMEM2_CACHE_VALUE;
    static const sc_lv<32> ap_const_lv32_F;
    static const sc_lv<32> ap_const_lv32_10;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<32> ap_const_lv32_1F;
    static const sc_lv<30> ap_const_lv30_1;
    static const sc_lv<30> ap_const_lv30_4;
    static const sc_lv<30> ap_const_lv30_5;
    static const sc_lv<30> ap_const_lv30_9;
    static const sc_lv<30> ap_const_lv30_B;
    static const sc_lv<30> ap_const_lv30_E;
    static const sc_lv<30> ap_const_lv30_11;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_clk_no_reset_();
    void thread_add_ln3244_fu_232_p2();
    void thread_add_ln3247_fu_248_p2();
    void thread_add_ln3248_fu_263_p2();
    void thread_add_ln3249_fu_278_p2();
    void thread_add_ln3251_fu_293_p2();
    void thread_add_ln3255_fu_308_p2();
    void thread_add_ln3257_fu_323_p2();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state10();
    void thread_ap_CS_fsm_state11();
    void thread_ap_CS_fsm_state12();
    void thread_ap_CS_fsm_state13();
    void thread_ap_CS_fsm_state14();
    void thread_ap_CS_fsm_state15();
    void thread_ap_CS_fsm_state16();
    void thread_ap_CS_fsm_state17();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state7();
    void thread_ap_CS_fsm_state8();
    void thread_ap_CS_fsm_state9();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_rst_n_inv();
    void thread_globalparams_partiti_fu_342_p1();
    void thread_globalparams_reducec_fu_346_p1();
    void thread_globalparams_runkern_fu_338_p1();
    void thread_globalparams_runsize_fu_358_p1();
    void thread_globalparams_statsal_fu_362_p1();
    void thread_globalparams_treedep_fu_354_p1();
    void thread_globalparams_vbegin_fu_350_p1();
    void thread_gmem0_ARVALID();
    void thread_gmem0_AWVALID();
    void thread_gmem0_BREADY();
    void thread_gmem0_RREADY();
    void thread_gmem0_WVALID();
    void thread_gmem1_ARVALID();
    void thread_gmem1_AWVALID();
    void thread_gmem1_BREADY();
    void thread_gmem1_RREADY();
    void thread_gmem1_WVALID();
    void thread_gmem2_ARADDR();
    void thread_gmem2_ARBURST();
    void thread_gmem2_ARCACHE();
    void thread_gmem2_ARID();
    void thread_gmem2_ARLEN();
    void thread_gmem2_ARLOCK();
    void thread_gmem2_ARPROT();
    void thread_gmem2_ARQOS();
    void thread_gmem2_ARREGION();
    void thread_gmem2_ARSIZE();
    void thread_gmem2_ARUSER();
    void thread_gmem2_ARVALID();
    void thread_gmem2_AWVALID();
    void thread_gmem2_BREADY();
    void thread_gmem2_RREADY();
    void thread_gmem2_WVALID();
    void thread_gmem2_blk_n_AR();
    void thread_gmem2_blk_n_R();
    void thread_grp_partitionandreduce0_fu_178_ap_start();
    void thread_kvstatsA5_fu_198_p4();
    void thread_p_cast_fu_208_p1();
    void thread_zext_ln3244_fu_238_p1();
    void thread_zext_ln3247_fu_253_p1();
    void thread_zext_ln3248_fu_268_p1();
    void thread_zext_ln3249_fu_283_p1();
    void thread_zext_ln3251_fu_298_p1();
    void thread_zext_ln3255_fu_313_p1();
    void thread_zext_ln3257_fu_328_p1();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
