puts "applying partitioning constraints generated by the Context Sensitive HLS Solver"
write_checkpoint ./before_opt_design.dcp -force 

	# startgroup
		# create_pblock custpblock1
		# resize_pblock custpblock1 -add {
			# SLICE_X0Y605:SLICE_X112Y713
			# DSP48E2_X0Y236:DSP48E2_X14Y277
			# RAMB18_X0Y242:RAMB18_X6Y283 
			# RAMB36_X0Y121:RAMB36_X6Y141
			# URAM288_X0Y164:URAM288_X1Y187
		# }
	# endgroup

	### top (1/6)
	# startgroup
		# create_pblock custpblock1
		# resize_pblock custpblock1 -add {
			# SLICE_X0Y600:SLICE_X232Y718
			# CFGIO_SITE_X0Y2:CFGIO_SITE_X0Y2
			# CMACE4_X0Y6:CMACE4_X0Y6
			# DSP48E2_X0Y234:DSP48E2_X31Y279
			# GTYE4_CHANNEL_X0Y40:GTYE4_CHANNEL_X0Y43
			# GTYE4_COMMON_X0Y10:GTYE4_COMMON_X0Y10
			# HPIOB_DCI_SNGL_X0Y40:HPIOB_DCI_SNGL_X0Y45
			# HPIO_RCLK_PRBS_X0Y10:HPIO_RCLK_PRBS_X0Y11
			# IOB_X0Y520:IOB_X0Y597
			# RAMB18_X0Y240:RAMB18_X13Y285
			# RAMB36_X0Y120:RAMB36_X13Y142
			# SYSMONE4_X0Y2:SYSMONE4_X0Y2
			# URAM288_X0Y160:URAM288_X4Y187
		# }
	# endgroup
	
	### top (1/6)
	# startgroup
		# create_pblock custpblock1
		# resize_pblock custpblock1 -add {
			# SLICE_X0Y600:SLICE_X232Y719
			# CFGIO_SITE_X0Y2:CFGIO_SITE_X0Y2
			# CMACE4_X0Y6:CMACE4_X0Y7
			# DSP48E2_X0Y234:DSP48E2_X31Y281
			# GTYE4_CHANNEL_X0Y40:GTYE4_CHANNEL_X1Y47
			# GTYE4_COMMON_X0Y10:GTYE4_COMMON_X1Y11
			# HPIOB_DCI_SNGL_X0Y40:HPIOB_DCI_SNGL_X0Y47
			# HPIO_RCLK_PRBS_X0Y10:HPIO_RCLK_PRBS_X0Y11
			# ILKNE4_X1Y3:ILKNE4_X1Y3
			# IOB_X0Y520:IOB_X0Y623
			# RAMB18_X0Y240:RAMB18_X13Y287
			# RAMB36_X0Y120:RAMB36_X13Y143
			# SYSMONE4_X0Y2:SYSMONE4_X0Y2
			# URAM288_X0Y160:URAM288_X4Y191
		# }
	# endgroup
	
	### SLR2
	startgroup
		create_pblock custpblock1
		resize_pblock custpblock1 -add {
			SLR2
		}
	endgroup
	
	# all the board area: (slr0-2)
	# startgroup
		# create_pblock custpblock1
		# resize_pblock custpblock1 -add {
			# SLICE_X0Y12:SLICE_X220Y715
			# CFGIO_SITE_X0Y0:CFGIO_SITE_X0Y2
			# CMACE4_X0Y0:CMACE4_X0Y6
			# CONFIG_SITE_X0Y0:CONFIG_SITE_X0Y2
			# DSP48E2_X0Y0:DSP48E2_X30Y279
			# GTYE4_CHANNEL_X0Y4:GTYE4_CHANNEL_X0Y43
			# GTYE4_COMMON_X0Y1:GTYE4_COMMON_X0Y10
			# HPIOB_DCI_SNGL_X0Y2:HPIOB_DCI_SNGL_X0Y45
			# HPIO_RCLK_PRBS_X0Y0:HPIO_RCLK_PRBS_X0Y11
			# ILKNE4_X1Y1:ILKNE4_X1Y1 ILKNE4_X0Y0:ILKNE4_X0Y2
			# IOB_X0Y26:IOB_X0Y597
			# PCIE40E4_X0Y0:PCIE40E4_X0Y1
			# PCIE4CE4_X0Y1:PCIE4CE4_X1Y1
			# RAMB18_X0Y6:RAMB18_X12Y285
			# RAMB36_X0Y3:RAMB36_X12Y142
			# SYSMONE4_X0Y0:SYSMONE4_X0Y2
			# URAM288_X0Y4:URAM288_X4Y187
		# }
	# endgroup
	
add_cells_to_pblock [get_pblocks custpblock1] [get_cells -regexp {
	# pfm_top_i/dynamic_region/.*/inst/A_IO_L3_in_U0
	# pfm_top_i/dynamic_region/topkernel_1/inst/grp_topkernelproc_1_fu_139/grp_dispatch_fu_554/grp_actit_fu_689
	# pfm_top_i/dynamic_region/topkernel_1/inst/grp_topkernelproc_1_fu_91
	pfm_top_i/dynamic_region/topkernel_1/inst
	pfm_top_i/dynamic_region/hmss_0
}] -clear_locs



