#!/bin/bash
#!/bin/bash

ROOTDIR="/home/oj2zf/Documents/ActsOfAGraph"
OUTPUTDIRNAME="outputs"
DEVICEPATH=/opt/xilinx/platforms/xilinx_u280_xdma_201920_3/xilinx_u280_xdma_201920_3.xpfm

# TESTKERNEL="RK"
TESTKERNEL="TESTKERNEL"

ALGORITHMABBRV="PR"
# ALGORITHMABBRV="CF"
# ALGORITHMABBRV="HITS"
# ALGORITHMABBRV="SPMV"
# ALGORITHMABBRV="BFS"
# ALGORITHMABBRV="SSSP"

#evaluation_type=EV_CREATENDGRAPH
evaluation_type=EV_PERFORMANCEOFALGORITHM
#evaluation_type=EV_IMPACTOF__ACTS_VERYBARE
#evaluation_type=EV_IMPACTOF__ACTS_BARE
#evaluation_type=EV_IMPACTOF__ACTS_PLUS_MEMLAYOUT
#evaluation_type=EV_IMPACTOF__ACTS_PLUS_MEMLAYOUT_PLUS_PARTITIONFUNC
#evaluation_type=EV_IMPACTOF__ACTS_PLUS_MEMLAYOUT_PLUS_PARTITIONFUNC_PLUS_REPARTITIONFUNC
#evaluation_type=EV_IMPACTOF__ACTS_PLUS_MEMLAYOUT_PLUS_PARTITIONFUNC_PLUS_REPARTITIONFUNC_PLUS_HYBRIDFUNC

XWARE="SW" 
# XWARE="HW"
ALGORITHM="${ALGORITHMABBRV}_ALGORITHM" 
SETUP_NAME="actgraph_${ALGORITHMABBRV}_sw"

BACKUPDIR_KERNELXCLBIN="${ROOTDIR}/${OUTPUTDIRNAME}/${SYNKERNELSPATHNAME}/goldenkernel${TESTKERNEL}${num_pes}.xclbin"
SYNLOGDIR_KERNELXCLBIN="${ROOTDIR}/${OUTPUTDIRNAME}/${SYNKERNELSPATHNAME}/goldenkernel${TESTKERNEL}${num_pes}.log"
SYNLOGDIR_SYNTHESISLOG="${ROOTDIR}/${OUTPUTDIRNAME}/${SYNKERNELSPATHNAME}/goldenkernel${TESTKERNEL}${num_pes}_report"

HWRESULTSBACKUP_DIR="${ROOTDIR}/${OUTPUTDIRNAME}/${HWRESULTSPATHNAME}/${ALGORITHMABBRV,,}/${TESTKERNEL,,}"
SWRESULTSBACKUP_DIR="${ROOTDIR}/${OUTPUTDIRNAME}/${SWRESULTSPATHNAME}/${ALGORITHMABBRV,,}/${TESTKERNEL,,}"
HWRESULTDIR_RESULT="${HWRESULTSBACKUP_DIR}/${TESTKERNEL}${TESTKERNELRG}${num_pes}PEs${numsubcputhreads}Ws${ALGORITHMABBRV}${XWARE}MHz.out"
SWRESULTDIR_RESULT="${SWRESULTSBACKUP_DIR}/${TESTKERNEL}${TESTKERNELRG}${num_pes}PEs${numsubcputhreads}Ws${ALGORITHMABBRV}${XWARE}MHz.out"

BACKUPDIR_NOHUPOUT="${ROOTDIR}/${OUTPUTDIRNAME}/${SYNKERNELSPATHNAME}/goldenkernel${TESTKERNEL}${TESTKERNELRG}${num_pes}PEs${numsubcputhreads}Ws${ALGORITHMABBRV}${XWARE}MHz.out"

RESULT_NAME="${ALGORITHMABBRV}${num_pes}PEs${numsubcputhreads}Ws${ALGORITHMABBRV}${XWARE}MHz"
PROFILESUMMARY_NAME="profile_summary_${ALGORITHMABBRV}_${num_pes}PEs${numsubcputhreads}Ws_${evaluation_type}_evp${evaluation_param0}"

# make generatesrcs XWARE=$XWARE ALGORITHM=$ALGORITHM EVALUATION_TYPE=$evaluation_type NUM_PEs=3 TESTKERNEL=$TESTKERNEL	
# make generatesrcs XWARE=$XWARE ALGORITHM=$ALGORITHM EVALUATION_TYPE=$evaluation_type NUM_PEs=16 TESTKERNEL=$TESTKERNEL	
make generatesrcs XWARE=$XWARE ALGORITHM=$ALGORITHM EVALUATION_TYPE=$evaluation_type NUM_PEs=20 TESTKERNEL=$TESTKERNEL	
# make generatesrcs XWARE=$XWARE ALGORITHM=$ALGORITHM EVALUATION_TYPE=$evaluation_type NUM_PEs=24 TESTKERNEL=$TESTKERNEL										

# faketime -f "-1y" make hw PLATFORM=$DEVICEPATH	

echo 'finished: successfully finished all processing'





