#ifndef CONFIG_PARAMS_H
#define CONFIG_PARAMS_H

// #define _GENERATE2DGRAPH //
// #define _GENERATEACTIVEVERTICES
// #define _GENERATESMARTGRAPH

#define RUNALLITERATIONS
#define _EVENWORLOADDISTRIBUTION
#define LAUNCHKERNEL
#define LOADKVDRAMS

#define STREAMEDGESSETUP
#endif




