#ifndef CONFIG_PARAMS_H
#define CONFIG_PARAMS_H

#define TESTKERNEL

// #define _GENERATE2DGRAPH //
// #define _GENERATEACTIVEVERTICES
// #define _GENERATESMARTGRAPH

#define RUNALLITERATIONS
#define _EVENWORLOADDISTRIBUTION
#define LAUNCHKERNEL
#define LOADKVDRAMS

#define STREAMEDGESSETUP

#define FORCEDFINISH_DONTCAREABOUTISVERTEXACTIVE
#define FORCEDFINISH_DONTCAREABOUTACTIVEVERTICESGENERATED

#define ENABLE_REDUCEPHASE
// #define ENABLE_LOADKVDRAM
#endif




