#ifndef CONFIG_PARAMS_H
#define CONFIG_PARAMS_H

#define ACTSFAST
#define MAXPERFORMANCE
#define MERGEEDGESANDKVDRAMWORKSPACE
#define MERGEPROCESSEDGESANDPARTITIONSTAGE // this must be used with COLLECTSTATSOFFLINE for now // FIXME. // appears in [loadgraph.cpp, actsfast.cpp, utility.cpp]

#define RUNALLITERATIONS
#define _EVENWORLOADDISTRIBUTION
#define LAUNCHKERNEL
#define LOADKVDRAMS
#define STREAMEDGESSETUP

// #define ENABLE_LOADKVDRAM
// #define ENABLE_REUSESAVEDCAPSULES
// #define ENABLE_PERFECTACCURACY //
// #define ENABLE_VOICEOUTREDUCEERRORS //
// #define ENABLE_VOICEOUTPROCESSEDGESERRORS //

#define FPGABUGCOMPLANT
#define ENABLE_APPROXIMATEPARTITIONWRITES // CRITICAL FIXME. FPGA hangs if this is disabled
#define HBMBUGCOMPLANT

// #define ACCESSFPGABY_ENQUEUEWRITEBUFFER // FIXME. causing extra latency
#endif




