// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1.3
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module getpartition (
        ap_ready,
        keyvalue_key,
        currentLOP,
        upperlimit,
        ap_return
);


output   ap_ready;
input  [31:0] keyvalue_key;
input  [31:0] currentLOP;
input  [31:0] upperlimit;
output  [4:0] ap_return;

wire   [31:0] shl_ln304_fu_48_p2;
wire   [31:0] sub_ln304_1_fu_54_p2;
wire   [31:0] sub_ln304_2_fu_60_p2;
wire   [31:0] sub_ln304_fu_42_p2;
wire   [31:0] add_ln304_fu_66_p2;
wire   [0:0] icmp_ln306_fu_78_p2;
wire   [31:0] val_fu_72_p2;
wire   [31:0] select_ln306_fu_84_p3;
wire   [26:0] tmp_fu_92_p4;
wire   [0:0] icmp_ln307_fu_102_p2;
wire   [4:0] trunc_ln307_fu_108_p1;
wire   [4:0] trunc_ln307_1_fu_112_p1;

assign add_ln304_fu_66_p2 = (32'd26 + sub_ln304_2_fu_60_p2);

assign ap_ready = 1'b1;

assign ap_return = ((icmp_ln307_fu_102_p2[0:0] === 1'b1) ? trunc_ln307_fu_108_p1 : trunc_ln307_1_fu_112_p1);

assign icmp_ln306_fu_78_p2 = ((keyvalue_key == 32'd123456789) ? 1'b1 : 1'b0);

assign icmp_ln307_fu_102_p2 = ((tmp_fu_92_p4 != 27'd0) ? 1'b1 : 1'b0);

assign select_ln306_fu_84_p3 = ((icmp_ln306_fu_78_p2[0:0] === 1'b1) ? 32'd0 : val_fu_72_p2);

assign shl_ln304_fu_48_p2 = currentLOP << 32'd2;

assign sub_ln304_1_fu_54_p2 = (32'd0 - shl_ln304_fu_48_p2);

assign sub_ln304_2_fu_60_p2 = (sub_ln304_1_fu_54_p2 - currentLOP);

assign sub_ln304_fu_42_p2 = (keyvalue_key - upperlimit);

assign tmp_fu_92_p4 = {{select_ln306_fu_84_p3[31:5]}};

assign trunc_ln307_1_fu_112_p1 = select_ln306_fu_84_p3[4:0];

assign trunc_ln307_fu_108_p1 = val_fu_72_p2[4:0];

assign val_fu_72_p2 = sub_ln304_fu_42_p2 >> add_ln304_fu_66_p2;

endmodule //getpartition
