// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1.3
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module readkeyvalues0_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        enable,
        m_axi_kvdram_V_AWVALID,
        m_axi_kvdram_V_AWREADY,
        m_axi_kvdram_V_AWADDR,
        m_axi_kvdram_V_AWID,
        m_axi_kvdram_V_AWLEN,
        m_axi_kvdram_V_AWSIZE,
        m_axi_kvdram_V_AWBURST,
        m_axi_kvdram_V_AWLOCK,
        m_axi_kvdram_V_AWCACHE,
        m_axi_kvdram_V_AWPROT,
        m_axi_kvdram_V_AWQOS,
        m_axi_kvdram_V_AWREGION,
        m_axi_kvdram_V_AWUSER,
        m_axi_kvdram_V_WVALID,
        m_axi_kvdram_V_WREADY,
        m_axi_kvdram_V_WDATA,
        m_axi_kvdram_V_WSTRB,
        m_axi_kvdram_V_WLAST,
        m_axi_kvdram_V_WID,
        m_axi_kvdram_V_WUSER,
        m_axi_kvdram_V_ARVALID,
        m_axi_kvdram_V_ARREADY,
        m_axi_kvdram_V_ARADDR,
        m_axi_kvdram_V_ARID,
        m_axi_kvdram_V_ARLEN,
        m_axi_kvdram_V_ARSIZE,
        m_axi_kvdram_V_ARBURST,
        m_axi_kvdram_V_ARLOCK,
        m_axi_kvdram_V_ARCACHE,
        m_axi_kvdram_V_ARPROT,
        m_axi_kvdram_V_ARQOS,
        m_axi_kvdram_V_ARREGION,
        m_axi_kvdram_V_ARUSER,
        m_axi_kvdram_V_RVALID,
        m_axi_kvdram_V_RREADY,
        m_axi_kvdram_V_RDATA,
        m_axi_kvdram_V_RLAST,
        m_axi_kvdram_V_RID,
        m_axi_kvdram_V_RUSER,
        m_axi_kvdram_V_RRESP,
        m_axi_kvdram_V_BVALID,
        m_axi_kvdram_V_BREADY,
        m_axi_kvdram_V_BRESP,
        m_axi_kvdram_V_BID,
        m_axi_kvdram_V_BUSER,
        kvdram_V_offset,
        buffer0_V_address0,
        buffer0_V_ce0,
        buffer0_V_we0,
        buffer0_V_d0,
        buffer1_V_address0,
        buffer1_V_ce0,
        buffer1_V_we0,
        buffer1_V_d0,
        buffer2_V_address0,
        buffer2_V_ce0,
        buffer2_V_we0,
        buffer2_V_d0,
        buffer3_V_address0,
        buffer3_V_ce0,
        buffer3_V_we0,
        buffer3_V_d0,
        baseaddress,
        offset_kvs,
        travstate_i_kvs,
        travstate_end_kvs
);

parameter    ap_ST_fsm_state1 = 9'd1;
parameter    ap_ST_fsm_state2 = 9'd2;
parameter    ap_ST_fsm_state3 = 9'd4;
parameter    ap_ST_fsm_state4 = 9'd8;
parameter    ap_ST_fsm_state5 = 9'd16;
parameter    ap_ST_fsm_state6 = 9'd32;
parameter    ap_ST_fsm_state7 = 9'd64;
parameter    ap_ST_fsm_state8 = 9'd128;
parameter    ap_ST_fsm_state9 = 9'd256;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [0:0] enable;
output   m_axi_kvdram_V_AWVALID;
input   m_axi_kvdram_V_AWREADY;
output  [31:0] m_axi_kvdram_V_AWADDR;
output  [0:0] m_axi_kvdram_V_AWID;
output  [31:0] m_axi_kvdram_V_AWLEN;
output  [2:0] m_axi_kvdram_V_AWSIZE;
output  [1:0] m_axi_kvdram_V_AWBURST;
output  [1:0] m_axi_kvdram_V_AWLOCK;
output  [3:0] m_axi_kvdram_V_AWCACHE;
output  [2:0] m_axi_kvdram_V_AWPROT;
output  [3:0] m_axi_kvdram_V_AWQOS;
output  [3:0] m_axi_kvdram_V_AWREGION;
output  [0:0] m_axi_kvdram_V_AWUSER;
output   m_axi_kvdram_V_WVALID;
input   m_axi_kvdram_V_WREADY;
output  [511:0] m_axi_kvdram_V_WDATA;
output  [63:0] m_axi_kvdram_V_WSTRB;
output   m_axi_kvdram_V_WLAST;
output  [0:0] m_axi_kvdram_V_WID;
output  [0:0] m_axi_kvdram_V_WUSER;
output   m_axi_kvdram_V_ARVALID;
input   m_axi_kvdram_V_ARREADY;
output  [31:0] m_axi_kvdram_V_ARADDR;
output  [0:0] m_axi_kvdram_V_ARID;
output  [31:0] m_axi_kvdram_V_ARLEN;
output  [2:0] m_axi_kvdram_V_ARSIZE;
output  [1:0] m_axi_kvdram_V_ARBURST;
output  [1:0] m_axi_kvdram_V_ARLOCK;
output  [3:0] m_axi_kvdram_V_ARCACHE;
output  [2:0] m_axi_kvdram_V_ARPROT;
output  [3:0] m_axi_kvdram_V_ARQOS;
output  [3:0] m_axi_kvdram_V_ARREGION;
output  [0:0] m_axi_kvdram_V_ARUSER;
input   m_axi_kvdram_V_RVALID;
output   m_axi_kvdram_V_RREADY;
input  [511:0] m_axi_kvdram_V_RDATA;
input   m_axi_kvdram_V_RLAST;
input  [0:0] m_axi_kvdram_V_RID;
input  [0:0] m_axi_kvdram_V_RUSER;
input  [1:0] m_axi_kvdram_V_RRESP;
input   m_axi_kvdram_V_BVALID;
output   m_axi_kvdram_V_BREADY;
input  [1:0] m_axi_kvdram_V_BRESP;
input  [0:0] m_axi_kvdram_V_BID;
input  [0:0] m_axi_kvdram_V_BUSER;
input  [25:0] kvdram_V_offset;
output  [8:0] buffer0_V_address0;
output   buffer0_V_ce0;
output   buffer0_V_we0;
output  [511:0] buffer0_V_d0;
output  [8:0] buffer1_V_address0;
output   buffer1_V_ce0;
output   buffer1_V_we0;
output  [511:0] buffer1_V_d0;
output  [8:0] buffer2_V_address0;
output   buffer2_V_ce0;
output   buffer2_V_we0;
output  [511:0] buffer2_V_d0;
output  [8:0] buffer3_V_address0;
output   buffer3_V_ce0;
output   buffer3_V_we0;
output  [511:0] buffer3_V_d0;
input  [24:0] baseaddress;
input  [31:0] offset_kvs;
input  [31:0] travstate_i_kvs;
input  [29:0] travstate_end_kvs;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg m_axi_kvdram_V_ARVALID;
reg m_axi_kvdram_V_RREADY;
reg buffer0_V_ce0;
reg buffer0_V_we0;
reg buffer1_V_ce0;
reg buffer1_V_we0;
reg buffer2_V_ce0;
reg buffer2_V_we0;
reg buffer3_V_ce0;
reg buffer3_V_we0;

(* fsm_encoding = "none" *) reg   [8:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] enable_read_read_fu_88_p2;
wire   [31:0] travstate_end_kvs_ca_fu_109_p1;
reg   [31:0] travstate_end_kvs_ca_reg_288;
wire   [31:0] i_fu_119_p2;
reg   [31:0] i_reg_298;
wire   [0:0] icmp_ln1234_fu_125_p2;
reg   [0:0] icmp_ln1234_reg_303;
wire   [31:0] select_ln1233_fu_145_p3;
reg   [31:0] select_ln1233_reg_308;
wire   [31:0] select_ln1233_4_fu_175_p3;
reg   [31:0] select_ln1233_4_reg_313;
wire    ap_CS_fsm_state3;
wire    grp_readkeyvalues0_166_fu_94_ap_ready;
wire    grp_readkeyvalues0_166_fu_94_ap_done;
wire   [31:0] select_ln1233_5_fu_205_p3;
reg   [31:0] select_ln1233_5_reg_318;
wire   [31:0] select_ln1233_6_fu_236_p3;
reg   [31:0] select_ln1233_6_reg_323;
wire   [31:0] add_ln1437_fu_244_p2;
reg   [31:0] add_ln1437_reg_328;
wire   [31:0] add_ln1438_fu_249_p2;
reg   [31:0] add_ln1438_reg_333;
wire    ap_CS_fsm_state5;
wire   [31:0] add_ln1439_fu_254_p2;
reg   [31:0] add_ln1439_reg_338;
wire    ap_CS_fsm_state7;
wire    grp_readkeyvalues0_166_fu_94_ap_start;
wire    grp_readkeyvalues0_166_fu_94_ap_idle;
wire    grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_AWVALID;
wire   [31:0] grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_AWADDR;
wire   [0:0] grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_AWID;
wire   [31:0] grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_AWLEN;
wire   [2:0] grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_AWSIZE;
wire   [1:0] grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_AWBURST;
wire   [1:0] grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_AWLOCK;
wire   [3:0] grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_AWCACHE;
wire   [2:0] grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_AWPROT;
wire   [3:0] grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_AWQOS;
wire   [3:0] grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_AWREGION;
wire   [0:0] grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_AWUSER;
wire    grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_WVALID;
wire   [511:0] grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_WDATA;
wire   [63:0] grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_WSTRB;
wire    grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_WLAST;
wire   [0:0] grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_WID;
wire   [0:0] grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_WUSER;
wire    grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_ARVALID;
wire   [31:0] grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_ARADDR;
wire   [0:0] grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_ARID;
wire   [31:0] grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_ARLEN;
wire   [2:0] grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_ARSIZE;
wire   [1:0] grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_ARBURST;
wire   [1:0] grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_ARLOCK;
wire   [3:0] grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_ARCACHE;
wire   [2:0] grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_ARPROT;
wire   [3:0] grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_ARQOS;
wire   [3:0] grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_ARREGION;
wire   [0:0] grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_ARUSER;
wire    grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_RREADY;
wire    grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_BREADY;
wire   [8:0] grp_readkeyvalues0_166_fu_94_buffer_V_address0;
wire    grp_readkeyvalues0_166_fu_94_buffer_V_ce0;
wire    grp_readkeyvalues0_166_fu_94_buffer_V_we0;
wire   [511:0] grp_readkeyvalues0_166_fu_94_buffer_V_d0;
reg   [31:0] grp_readkeyvalues0_166_fu_94_offset_kvs;
reg   [31:0] grp_readkeyvalues0_166_fu_94_size_kvs;
reg    grp_readkeyvalues0_166_fu_94_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
wire   [31:0] chunk0_size_fu_131_p2;
wire   [0:0] icmp_ln1233_fu_113_p2;
wire   [31:0] select_ln1234_fu_137_p3;
wire   [31:0] i_4_fu_153_p2;
wire   [0:0] icmp_ln1234_4_fu_158_p2;
wire   [31:0] chunk1_size_fu_163_p2;
wire   [31:0] select_ln1234_4_fu_167_p3;
wire   [31:0] i_5_fu_182_p2;
wire   [0:0] icmp_ln1234_5_fu_187_p2;
wire   [31:0] chunk2_size_fu_192_p2;
wire   [31:0] select_ln1234_5_fu_197_p3;
wire   [31:0] add_ln1234_fu_213_p2;
wire   [0:0] icmp_ln1234_6_fu_218_p2;
wire   [31:0] chunk3_size_fu_223_p2;
wire   [31:0] select_ln1234_6_fu_228_p3;
reg    ap_block_state9_on_subcall_done;
reg   [8:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 9'd1;
#0 grp_readkeyvalues0_166_fu_94_ap_start_reg = 1'b0;
end

readkeyvalues0_166 grp_readkeyvalues0_166_fu_94(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_readkeyvalues0_166_fu_94_ap_start),
    .ap_done(grp_readkeyvalues0_166_fu_94_ap_done),
    .ap_idle(grp_readkeyvalues0_166_fu_94_ap_idle),
    .ap_ready(grp_readkeyvalues0_166_fu_94_ap_ready),
    .m_axi_kvdram_V_AWVALID(grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_AWVALID),
    .m_axi_kvdram_V_AWREADY(1'b0),
    .m_axi_kvdram_V_AWADDR(grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_AWADDR),
    .m_axi_kvdram_V_AWID(grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_AWID),
    .m_axi_kvdram_V_AWLEN(grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_AWLEN),
    .m_axi_kvdram_V_AWSIZE(grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_AWSIZE),
    .m_axi_kvdram_V_AWBURST(grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_AWBURST),
    .m_axi_kvdram_V_AWLOCK(grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_AWLOCK),
    .m_axi_kvdram_V_AWCACHE(grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_AWCACHE),
    .m_axi_kvdram_V_AWPROT(grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_AWPROT),
    .m_axi_kvdram_V_AWQOS(grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_AWQOS),
    .m_axi_kvdram_V_AWREGION(grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_AWREGION),
    .m_axi_kvdram_V_AWUSER(grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_AWUSER),
    .m_axi_kvdram_V_WVALID(grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_WVALID),
    .m_axi_kvdram_V_WREADY(1'b0),
    .m_axi_kvdram_V_WDATA(grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_WDATA),
    .m_axi_kvdram_V_WSTRB(grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_WSTRB),
    .m_axi_kvdram_V_WLAST(grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_WLAST),
    .m_axi_kvdram_V_WID(grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_WID),
    .m_axi_kvdram_V_WUSER(grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_WUSER),
    .m_axi_kvdram_V_ARVALID(grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_ARVALID),
    .m_axi_kvdram_V_ARREADY(m_axi_kvdram_V_ARREADY),
    .m_axi_kvdram_V_ARADDR(grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_ARADDR),
    .m_axi_kvdram_V_ARID(grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_ARID),
    .m_axi_kvdram_V_ARLEN(grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_ARLEN),
    .m_axi_kvdram_V_ARSIZE(grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_ARSIZE),
    .m_axi_kvdram_V_ARBURST(grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_ARBURST),
    .m_axi_kvdram_V_ARLOCK(grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_ARLOCK),
    .m_axi_kvdram_V_ARCACHE(grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_ARCACHE),
    .m_axi_kvdram_V_ARPROT(grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_ARPROT),
    .m_axi_kvdram_V_ARQOS(grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_ARQOS),
    .m_axi_kvdram_V_ARREGION(grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_ARREGION),
    .m_axi_kvdram_V_ARUSER(grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_ARUSER),
    .m_axi_kvdram_V_RVALID(m_axi_kvdram_V_RVALID),
    .m_axi_kvdram_V_RREADY(grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_RREADY),
    .m_axi_kvdram_V_RDATA(m_axi_kvdram_V_RDATA),
    .m_axi_kvdram_V_RLAST(m_axi_kvdram_V_RLAST),
    .m_axi_kvdram_V_RID(m_axi_kvdram_V_RID),
    .m_axi_kvdram_V_RUSER(m_axi_kvdram_V_RUSER),
    .m_axi_kvdram_V_RRESP(m_axi_kvdram_V_RRESP),
    .m_axi_kvdram_V_BVALID(1'b0),
    .m_axi_kvdram_V_BREADY(grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_BREADY),
    .m_axi_kvdram_V_BRESP(2'd0),
    .m_axi_kvdram_V_BID(1'd0),
    .m_axi_kvdram_V_BUSER(1'd0),
    .kvdram_V_offset(kvdram_V_offset),
    .buffer_V_address0(grp_readkeyvalues0_166_fu_94_buffer_V_address0),
    .buffer_V_ce0(grp_readkeyvalues0_166_fu_94_buffer_V_ce0),
    .buffer_V_we0(grp_readkeyvalues0_166_fu_94_buffer_V_we0),
    .buffer_V_d0(grp_readkeyvalues0_166_fu_94_buffer_V_d0),
    .baseaddress(baseaddress),
    .offset_kvs(grp_readkeyvalues0_166_fu_94_offset_kvs),
    .size_kvs(grp_readkeyvalues0_166_fu_94_size_kvs)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_readkeyvalues0_166_fu_94_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state2))) begin
            grp_readkeyvalues0_166_fu_94_ap_start_reg <= 1'b1;
        end else if ((grp_readkeyvalues0_166_fu_94_ap_ready == 1'b1)) begin
            grp_readkeyvalues0_166_fu_94_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_readkeyvalues0_166_fu_94_ap_done == 1'b1))) begin
        add_ln1437_reg_328 <= add_ln1437_fu_244_p2;
        select_ln1233_4_reg_313 <= select_ln1233_4_fu_175_p3;
        select_ln1233_5_reg_318 <= select_ln1233_5_fu_205_p3;
        select_ln1233_6_reg_323 <= select_ln1233_6_fu_236_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (grp_readkeyvalues0_166_fu_94_ap_done == 1'b1))) begin
        add_ln1438_reg_333 <= add_ln1438_fu_249_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state7) & (grp_readkeyvalues0_166_fu_94_ap_done == 1'b1))) begin
        add_ln1439_reg_338 <= add_ln1439_fu_254_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (enable == 1'd1))) begin
        i_reg_298 <= i_fu_119_p2;
        icmp_ln1234_reg_303 <= icmp_ln1234_fu_125_p2;
        select_ln1233_reg_308 <= select_ln1233_fu_145_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        travstate_end_kvs_ca_reg_288[29 : 0] <= travstate_end_kvs_ca_fu_109_p1[29 : 0];
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state9_on_subcall_done) & (1'b1 == ap_CS_fsm_state9)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state9_on_subcall_done) & (1'b1 == ap_CS_fsm_state9))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        buffer0_V_ce0 = grp_readkeyvalues0_166_fu_94_buffer_V_ce0;
    end else begin
        buffer0_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        buffer0_V_we0 = grp_readkeyvalues0_166_fu_94_buffer_V_we0;
    end else begin
        buffer0_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        buffer1_V_ce0 = grp_readkeyvalues0_166_fu_94_buffer_V_ce0;
    end else begin
        buffer1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        buffer1_V_we0 = grp_readkeyvalues0_166_fu_94_buffer_V_we0;
    end else begin
        buffer1_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        buffer2_V_ce0 = grp_readkeyvalues0_166_fu_94_buffer_V_ce0;
    end else begin
        buffer2_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        buffer2_V_we0 = grp_readkeyvalues0_166_fu_94_buffer_V_we0;
    end else begin
        buffer2_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) & (enable == 1'd1))) begin
        buffer3_V_ce0 = grp_readkeyvalues0_166_fu_94_buffer_V_ce0;
    end else begin
        buffer3_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) & (enable == 1'd1))) begin
        buffer3_V_we0 = grp_readkeyvalues0_166_fu_94_buffer_V_we0;
    end else begin
        buffer3_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) & (enable == 1'd1))) begin
        grp_readkeyvalues0_166_fu_94_offset_kvs = add_ln1439_reg_338;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_readkeyvalues0_166_fu_94_offset_kvs = add_ln1438_reg_333;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_readkeyvalues0_166_fu_94_offset_kvs = add_ln1437_reg_328;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_readkeyvalues0_166_fu_94_offset_kvs = offset_kvs;
    end else begin
        grp_readkeyvalues0_166_fu_94_offset_kvs = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) & (enable == 1'd1))) begin
        grp_readkeyvalues0_166_fu_94_size_kvs = select_ln1233_6_reg_323;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_readkeyvalues0_166_fu_94_size_kvs = select_ln1233_5_reg_318;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_readkeyvalues0_166_fu_94_size_kvs = select_ln1233_4_reg_313;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_readkeyvalues0_166_fu_94_size_kvs = select_ln1233_reg_308;
    end else begin
        grp_readkeyvalues0_166_fu_94_size_kvs = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state3) | ((1'b1 == ap_CS_fsm_state9) & (enable == 1'd1)))) begin
        m_axi_kvdram_V_ARVALID = grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_ARVALID;
    end else begin
        m_axi_kvdram_V_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state3) | ((1'b1 == ap_CS_fsm_state9) & (enable == 1'd1)))) begin
        m_axi_kvdram_V_RREADY = grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_RREADY;
    end else begin
        m_axi_kvdram_V_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((enable_read_read_fu_88_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (enable == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_readkeyvalues0_166_fu_94_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (grp_readkeyvalues0_166_fu_94_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (grp_readkeyvalues0_166_fu_94_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((1'b0 == ap_block_state9_on_subcall_done) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1234_fu_213_p2 = (travstate_i_kvs + 32'd2048);

assign add_ln1437_fu_244_p2 = (offset_kvs + 32'd512);

assign add_ln1438_fu_249_p2 = (offset_kvs + 32'd1024);

assign add_ln1439_fu_254_p2 = (offset_kvs + 32'd1536);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state9_on_subcall_done = ((grp_readkeyvalues0_166_fu_94_ap_done == 1'b0) & (enable == 1'd1));
end

assign buffer0_V_address0 = grp_readkeyvalues0_166_fu_94_buffer_V_address0;

assign buffer0_V_d0 = grp_readkeyvalues0_166_fu_94_buffer_V_d0;

assign buffer1_V_address0 = grp_readkeyvalues0_166_fu_94_buffer_V_address0;

assign buffer1_V_d0 = grp_readkeyvalues0_166_fu_94_buffer_V_d0;

assign buffer2_V_address0 = grp_readkeyvalues0_166_fu_94_buffer_V_address0;

assign buffer2_V_d0 = grp_readkeyvalues0_166_fu_94_buffer_V_d0;

assign buffer3_V_address0 = grp_readkeyvalues0_166_fu_94_buffer_V_address0;

assign buffer3_V_d0 = grp_readkeyvalues0_166_fu_94_buffer_V_d0;

assign chunk0_size_fu_131_p2 = (travstate_end_kvs_ca_fu_109_p1 - travstate_i_kvs);

assign chunk1_size_fu_163_p2 = (travstate_end_kvs_ca_reg_288 - i_reg_298);

assign chunk2_size_fu_192_p2 = (travstate_end_kvs_ca_reg_288 - i_4_fu_153_p2);

assign chunk3_size_fu_223_p2 = (travstate_end_kvs_ca_reg_288 - i_5_fu_182_p2);

assign enable_read_read_fu_88_p2 = enable;

assign grp_readkeyvalues0_166_fu_94_ap_start = grp_readkeyvalues0_166_fu_94_ap_start_reg;

assign i_4_fu_153_p2 = (travstate_i_kvs + 32'd1024);

assign i_5_fu_182_p2 = (travstate_i_kvs + 32'd1536);

assign i_fu_119_p2 = (travstate_i_kvs + 32'd512);

assign icmp_ln1233_fu_113_p2 = ((travstate_end_kvs_ca_fu_109_p1 < travstate_i_kvs) ? 1'b1 : 1'b0);

assign icmp_ln1234_4_fu_158_p2 = ((i_4_fu_153_p2 > travstate_end_kvs_ca_reg_288) ? 1'b1 : 1'b0);

assign icmp_ln1234_5_fu_187_p2 = ((i_5_fu_182_p2 > travstate_end_kvs_ca_reg_288) ? 1'b1 : 1'b0);

assign icmp_ln1234_6_fu_218_p2 = ((add_ln1234_fu_213_p2 > travstate_end_kvs_ca_reg_288) ? 1'b1 : 1'b0);

assign icmp_ln1234_fu_125_p2 = ((i_fu_119_p2 > travstate_end_kvs_ca_fu_109_p1) ? 1'b1 : 1'b0);

assign m_axi_kvdram_V_ARADDR = grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_ARADDR;

assign m_axi_kvdram_V_ARBURST = grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_ARBURST;

assign m_axi_kvdram_V_ARCACHE = grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_ARCACHE;

assign m_axi_kvdram_V_ARID = grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_ARID;

assign m_axi_kvdram_V_ARLEN = grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_ARLEN;

assign m_axi_kvdram_V_ARLOCK = grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_ARLOCK;

assign m_axi_kvdram_V_ARPROT = grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_ARPROT;

assign m_axi_kvdram_V_ARQOS = grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_ARQOS;

assign m_axi_kvdram_V_ARREGION = grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_ARREGION;

assign m_axi_kvdram_V_ARSIZE = grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_ARSIZE;

assign m_axi_kvdram_V_ARUSER = grp_readkeyvalues0_166_fu_94_m_axi_kvdram_V_ARUSER;

assign m_axi_kvdram_V_AWADDR = 32'd0;

assign m_axi_kvdram_V_AWBURST = 2'd0;

assign m_axi_kvdram_V_AWCACHE = 4'd0;

assign m_axi_kvdram_V_AWID = 1'd0;

assign m_axi_kvdram_V_AWLEN = 32'd0;

assign m_axi_kvdram_V_AWLOCK = 2'd0;

assign m_axi_kvdram_V_AWPROT = 3'd0;

assign m_axi_kvdram_V_AWQOS = 4'd0;

assign m_axi_kvdram_V_AWREGION = 4'd0;

assign m_axi_kvdram_V_AWSIZE = 3'd0;

assign m_axi_kvdram_V_AWUSER = 1'd0;

assign m_axi_kvdram_V_AWVALID = 1'b0;

assign m_axi_kvdram_V_BREADY = 1'b0;

assign m_axi_kvdram_V_WDATA = 512'd0;

assign m_axi_kvdram_V_WID = 1'd0;

assign m_axi_kvdram_V_WLAST = 1'b0;

assign m_axi_kvdram_V_WSTRB = 64'd0;

assign m_axi_kvdram_V_WUSER = 1'd0;

assign m_axi_kvdram_V_WVALID = 1'b0;

assign select_ln1233_4_fu_175_p3 = ((icmp_ln1234_reg_303[0:0] === 1'b1) ? 32'd0 : select_ln1234_4_fu_167_p3);

assign select_ln1233_5_fu_205_p3 = ((icmp_ln1234_4_fu_158_p2[0:0] === 1'b1) ? 32'd0 : select_ln1234_5_fu_197_p3);

assign select_ln1233_6_fu_236_p3 = ((icmp_ln1234_5_fu_187_p2[0:0] === 1'b1) ? 32'd0 : select_ln1234_6_fu_228_p3);

assign select_ln1233_fu_145_p3 = ((icmp_ln1233_fu_113_p2[0:0] === 1'b1) ? 32'd0 : select_ln1234_fu_137_p3);

assign select_ln1234_4_fu_167_p3 = ((icmp_ln1234_4_fu_158_p2[0:0] === 1'b1) ? chunk1_size_fu_163_p2 : 32'd512);

assign select_ln1234_5_fu_197_p3 = ((icmp_ln1234_5_fu_187_p2[0:0] === 1'b1) ? chunk2_size_fu_192_p2 : 32'd512);

assign select_ln1234_6_fu_228_p3 = ((icmp_ln1234_6_fu_218_p2[0:0] === 1'b1) ? chunk3_size_fu_223_p2 : 32'd512);

assign select_ln1234_fu_137_p3 = ((icmp_ln1234_fu_125_p2[0:0] === 1'b1) ? chunk0_size_fu_131_p2 : 32'd512);

assign travstate_end_kvs_ca_fu_109_p1 = travstate_end_kvs;

always @ (posedge ap_clk) begin
    travstate_end_kvs_ca_reg_288[31:30] <= 2'b00;
end

endmodule //readkeyvalues0_2
