// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1.3
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="topkernel,hls_ip_2019_1_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xcvu9p-fsgd2104-2-i,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.750000,HLS_SYN_LAT=166182987,HLS_SYN_TPT=none,HLS_SYN_MEM=736,HLS_SYN_DSP=0,HLS_SYN_FF=29774,HLS_SYN_LUT=40484,HLS_VERSION=2019_1_3}" *)

module topkernel (
        ap_clk,
        ap_rst_n,
        m_axi_gmem0_AWVALID,
        m_axi_gmem0_AWREADY,
        m_axi_gmem0_AWADDR,
        m_axi_gmem0_AWID,
        m_axi_gmem0_AWLEN,
        m_axi_gmem0_AWSIZE,
        m_axi_gmem0_AWBURST,
        m_axi_gmem0_AWLOCK,
        m_axi_gmem0_AWCACHE,
        m_axi_gmem0_AWPROT,
        m_axi_gmem0_AWQOS,
        m_axi_gmem0_AWREGION,
        m_axi_gmem0_AWUSER,
        m_axi_gmem0_WVALID,
        m_axi_gmem0_WREADY,
        m_axi_gmem0_WDATA,
        m_axi_gmem0_WSTRB,
        m_axi_gmem0_WLAST,
        m_axi_gmem0_WID,
        m_axi_gmem0_WUSER,
        m_axi_gmem0_ARVALID,
        m_axi_gmem0_ARREADY,
        m_axi_gmem0_ARADDR,
        m_axi_gmem0_ARID,
        m_axi_gmem0_ARLEN,
        m_axi_gmem0_ARSIZE,
        m_axi_gmem0_ARBURST,
        m_axi_gmem0_ARLOCK,
        m_axi_gmem0_ARCACHE,
        m_axi_gmem0_ARPROT,
        m_axi_gmem0_ARQOS,
        m_axi_gmem0_ARREGION,
        m_axi_gmem0_ARUSER,
        m_axi_gmem0_RVALID,
        m_axi_gmem0_RREADY,
        m_axi_gmem0_RDATA,
        m_axi_gmem0_RLAST,
        m_axi_gmem0_RID,
        m_axi_gmem0_RUSER,
        m_axi_gmem0_RRESP,
        m_axi_gmem0_BVALID,
        m_axi_gmem0_BREADY,
        m_axi_gmem0_BRESP,
        m_axi_gmem0_BID,
        m_axi_gmem0_BUSER,
        m_axi_gmem1_AWVALID,
        m_axi_gmem1_AWREADY,
        m_axi_gmem1_AWADDR,
        m_axi_gmem1_AWID,
        m_axi_gmem1_AWLEN,
        m_axi_gmem1_AWSIZE,
        m_axi_gmem1_AWBURST,
        m_axi_gmem1_AWLOCK,
        m_axi_gmem1_AWCACHE,
        m_axi_gmem1_AWPROT,
        m_axi_gmem1_AWQOS,
        m_axi_gmem1_AWREGION,
        m_axi_gmem1_AWUSER,
        m_axi_gmem1_WVALID,
        m_axi_gmem1_WREADY,
        m_axi_gmem1_WDATA,
        m_axi_gmem1_WSTRB,
        m_axi_gmem1_WLAST,
        m_axi_gmem1_WID,
        m_axi_gmem1_WUSER,
        m_axi_gmem1_ARVALID,
        m_axi_gmem1_ARREADY,
        m_axi_gmem1_ARADDR,
        m_axi_gmem1_ARID,
        m_axi_gmem1_ARLEN,
        m_axi_gmem1_ARSIZE,
        m_axi_gmem1_ARBURST,
        m_axi_gmem1_ARLOCK,
        m_axi_gmem1_ARCACHE,
        m_axi_gmem1_ARPROT,
        m_axi_gmem1_ARQOS,
        m_axi_gmem1_ARREGION,
        m_axi_gmem1_ARUSER,
        m_axi_gmem1_RVALID,
        m_axi_gmem1_RREADY,
        m_axi_gmem1_RDATA,
        m_axi_gmem1_RLAST,
        m_axi_gmem1_RID,
        m_axi_gmem1_RUSER,
        m_axi_gmem1_RRESP,
        m_axi_gmem1_BVALID,
        m_axi_gmem1_BREADY,
        m_axi_gmem1_BRESP,
        m_axi_gmem1_BID,
        m_axi_gmem1_BUSER,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 14'd1;
parameter    ap_ST_fsm_state2 = 14'd2;
parameter    ap_ST_fsm_state3 = 14'd4;
parameter    ap_ST_fsm_state4 = 14'd8;
parameter    ap_ST_fsm_state5 = 14'd16;
parameter    ap_ST_fsm_state6 = 14'd32;
parameter    ap_ST_fsm_state7 = 14'd64;
parameter    ap_ST_fsm_state8 = 14'd128;
parameter    ap_ST_fsm_state9 = 14'd256;
parameter    ap_ST_fsm_state10 = 14'd512;
parameter    ap_ST_fsm_state11 = 14'd1024;
parameter    ap_ST_fsm_state12 = 14'd2048;
parameter    ap_ST_fsm_state13 = 14'd4096;
parameter    ap_ST_fsm_state14 = 14'd8192;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 5;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM0_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM0_ADDR_WIDTH = 32;
parameter    C_M_AXI_GMEM0_DATA_WIDTH = 512;
parameter    C_M_AXI_GMEM0_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_USER_VALUE = 0;
parameter    C_M_AXI_GMEM0_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM0_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM1_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM1_ADDR_WIDTH = 32;
parameter    C_M_AXI_GMEM1_DATA_WIDTH = 64;
parameter    C_M_AXI_GMEM1_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_USER_VALUE = 0;
parameter    C_M_AXI_GMEM1_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM1_CACHE_VALUE = 3;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM0_WSTRB_WIDTH = (512 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM1_WSTRB_WIDTH = (64 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_gmem0_AWVALID;
input   m_axi_gmem0_AWREADY;
output  [C_M_AXI_GMEM0_ADDR_WIDTH - 1:0] m_axi_gmem0_AWADDR;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_AWID;
output  [7:0] m_axi_gmem0_AWLEN;
output  [2:0] m_axi_gmem0_AWSIZE;
output  [1:0] m_axi_gmem0_AWBURST;
output  [1:0] m_axi_gmem0_AWLOCK;
output  [3:0] m_axi_gmem0_AWCACHE;
output  [2:0] m_axi_gmem0_AWPROT;
output  [3:0] m_axi_gmem0_AWQOS;
output  [3:0] m_axi_gmem0_AWREGION;
output  [C_M_AXI_GMEM0_AWUSER_WIDTH - 1:0] m_axi_gmem0_AWUSER;
output   m_axi_gmem0_WVALID;
input   m_axi_gmem0_WREADY;
output  [C_M_AXI_GMEM0_DATA_WIDTH - 1:0] m_axi_gmem0_WDATA;
output  [C_M_AXI_GMEM0_WSTRB_WIDTH - 1:0] m_axi_gmem0_WSTRB;
output   m_axi_gmem0_WLAST;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_WID;
output  [C_M_AXI_GMEM0_WUSER_WIDTH - 1:0] m_axi_gmem0_WUSER;
output   m_axi_gmem0_ARVALID;
input   m_axi_gmem0_ARREADY;
output  [C_M_AXI_GMEM0_ADDR_WIDTH - 1:0] m_axi_gmem0_ARADDR;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_ARID;
output  [7:0] m_axi_gmem0_ARLEN;
output  [2:0] m_axi_gmem0_ARSIZE;
output  [1:0] m_axi_gmem0_ARBURST;
output  [1:0] m_axi_gmem0_ARLOCK;
output  [3:0] m_axi_gmem0_ARCACHE;
output  [2:0] m_axi_gmem0_ARPROT;
output  [3:0] m_axi_gmem0_ARQOS;
output  [3:0] m_axi_gmem0_ARREGION;
output  [C_M_AXI_GMEM0_ARUSER_WIDTH - 1:0] m_axi_gmem0_ARUSER;
input   m_axi_gmem0_RVALID;
output   m_axi_gmem0_RREADY;
input  [C_M_AXI_GMEM0_DATA_WIDTH - 1:0] m_axi_gmem0_RDATA;
input   m_axi_gmem0_RLAST;
input  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_RID;
input  [C_M_AXI_GMEM0_RUSER_WIDTH - 1:0] m_axi_gmem0_RUSER;
input  [1:0] m_axi_gmem0_RRESP;
input   m_axi_gmem0_BVALID;
output   m_axi_gmem0_BREADY;
input  [1:0] m_axi_gmem0_BRESP;
input  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_BID;
input  [C_M_AXI_GMEM0_BUSER_WIDTH - 1:0] m_axi_gmem0_BUSER;
output   m_axi_gmem1_AWVALID;
input   m_axi_gmem1_AWREADY;
output  [C_M_AXI_GMEM1_ADDR_WIDTH - 1:0] m_axi_gmem1_AWADDR;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_AWID;
output  [7:0] m_axi_gmem1_AWLEN;
output  [2:0] m_axi_gmem1_AWSIZE;
output  [1:0] m_axi_gmem1_AWBURST;
output  [1:0] m_axi_gmem1_AWLOCK;
output  [3:0] m_axi_gmem1_AWCACHE;
output  [2:0] m_axi_gmem1_AWPROT;
output  [3:0] m_axi_gmem1_AWQOS;
output  [3:0] m_axi_gmem1_AWREGION;
output  [C_M_AXI_GMEM1_AWUSER_WIDTH - 1:0] m_axi_gmem1_AWUSER;
output   m_axi_gmem1_WVALID;
input   m_axi_gmem1_WREADY;
output  [C_M_AXI_GMEM1_DATA_WIDTH - 1:0] m_axi_gmem1_WDATA;
output  [C_M_AXI_GMEM1_WSTRB_WIDTH - 1:0] m_axi_gmem1_WSTRB;
output   m_axi_gmem1_WLAST;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_WID;
output  [C_M_AXI_GMEM1_WUSER_WIDTH - 1:0] m_axi_gmem1_WUSER;
output   m_axi_gmem1_ARVALID;
input   m_axi_gmem1_ARREADY;
output  [C_M_AXI_GMEM1_ADDR_WIDTH - 1:0] m_axi_gmem1_ARADDR;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_ARID;
output  [7:0] m_axi_gmem1_ARLEN;
output  [2:0] m_axi_gmem1_ARSIZE;
output  [1:0] m_axi_gmem1_ARBURST;
output  [1:0] m_axi_gmem1_ARLOCK;
output  [3:0] m_axi_gmem1_ARCACHE;
output  [2:0] m_axi_gmem1_ARPROT;
output  [3:0] m_axi_gmem1_ARQOS;
output  [3:0] m_axi_gmem1_ARREGION;
output  [C_M_AXI_GMEM1_ARUSER_WIDTH - 1:0] m_axi_gmem1_ARUSER;
input   m_axi_gmem1_RVALID;
output   m_axi_gmem1_RREADY;
input  [C_M_AXI_GMEM1_DATA_WIDTH - 1:0] m_axi_gmem1_RDATA;
input   m_axi_gmem1_RLAST;
input  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_RID;
input  [C_M_AXI_GMEM1_RUSER_WIDTH - 1:0] m_axi_gmem1_RUSER;
input  [1:0] m_axi_gmem1_RRESP;
input   m_axi_gmem1_BVALID;
output   m_axi_gmem1_BREADY;
input  [1:0] m_axi_gmem1_BRESP;
input  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_BID;
input  [C_M_AXI_GMEM1_BUSER_WIDTH - 1:0] m_axi_gmem1_BUSER;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [13:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [31:0] kvsetdramA_V;
wire   [31:0] kvdramA;
reg    gmem1_blk_n_AR;
wire    ap_CS_fsm_state2;
reg    gmem1_blk_n_R;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state12;
reg    gmem0_AWVALID;
wire    gmem0_AWREADY;
reg    gmem0_WVALID;
wire    gmem0_WREADY;
reg    gmem0_ARVALID;
wire    gmem0_ARREADY;
wire    gmem0_RVALID;
reg    gmem0_RREADY;
wire   [511:0] gmem0_RDATA;
wire    gmem0_RLAST;
wire   [0:0] gmem0_RID;
wire   [0:0] gmem0_RUSER;
wire   [1:0] gmem0_RRESP;
wire    gmem0_BVALID;
reg    gmem0_BREADY;
wire   [1:0] gmem0_BRESP;
wire   [0:0] gmem0_BID;
wire   [0:0] gmem0_BUSER;
reg    gmem1_AWVALID;
wire    gmem1_AWREADY;
reg    gmem1_WVALID;
wire    gmem1_WREADY;
reg    gmem1_ARVALID;
wire    gmem1_ARREADY;
reg   [31:0] gmem1_ARADDR;
reg   [0:0] gmem1_ARID;
reg   [31:0] gmem1_ARLEN;
reg   [2:0] gmem1_ARSIZE;
reg   [1:0] gmem1_ARBURST;
reg   [1:0] gmem1_ARLOCK;
reg   [3:0] gmem1_ARCACHE;
reg   [2:0] gmem1_ARPROT;
reg   [3:0] gmem1_ARQOS;
reg   [3:0] gmem1_ARREGION;
reg   [0:0] gmem1_ARUSER;
wire    gmem1_RVALID;
reg    gmem1_RREADY;
wire   [63:0] gmem1_RDATA;
wire    gmem1_RLAST;
wire   [0:0] gmem1_RID;
wire   [0:0] gmem1_RUSER;
wire   [1:0] gmem1_RRESP;
wire    gmem1_BVALID;
reg    gmem1_BREADY;
wire   [1:0] gmem1_BRESP;
wire   [0:0] gmem1_BID;
wire   [0:0] gmem1_BUSER;
wire   [28:0] kvdramA3_fu_138_p4;
reg   [28:0] kvdramA3_reg_239;
wire   [29:0] p_cast_fu_148_p1;
reg   [29:0] p_cast_reg_244;
reg   [25:0] kvsetdramA_V1_reg_251;
wire   [29:0] add_ln1547_fu_162_p2;
reg   [29:0] add_ln1547_reg_256;
wire   [29:0] add_ln1548_fu_178_p2;
reg   [29:0] add_ln1548_reg_267;
wire   [29:0] add_ln1550_fu_193_p2;
reg   [29:0] add_ln1550_reg_278;
wire   [29:0] add_ln1551_fu_208_p2;
reg   [29:0] add_ln1551_reg_289;
wire   [31:0] globalparams_reducec_fu_223_p1;
reg   [31:0] globalparams_reducec_reg_300;
wire   [31:0] globalparams_vbegin_fu_227_p1;
reg   [31:0] globalparams_vbegin_reg_305;
wire   [31:0] globalparams_treedep_fu_231_p1;
reg   [31:0] globalparams_treedep_reg_310;
wire   [31:0] globalparams_LLOPnum_fu_235_p1;
reg   [31:0] globalparams_LLOPnum_reg_315;
wire    grp_generatepartitions0_fu_124_ap_start;
wire    grp_generatepartitions0_fu_124_ap_done;
wire    grp_generatepartitions0_fu_124_ap_idle;
wire    grp_generatepartitions0_fu_124_ap_ready;
wire    grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_AWVALID;
wire   [31:0] grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_AWADDR;
wire   [0:0] grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_AWID;
wire   [31:0] grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_AWLEN;
wire   [2:0] grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_AWSIZE;
wire   [1:0] grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_AWBURST;
wire   [1:0] grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_AWLOCK;
wire   [3:0] grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_AWCACHE;
wire   [2:0] grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_AWPROT;
wire   [3:0] grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_AWQOS;
wire   [3:0] grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_AWREGION;
wire   [0:0] grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_AWUSER;
wire    grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_WVALID;
wire   [511:0] grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_WDATA;
wire   [63:0] grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_WSTRB;
wire    grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_WLAST;
wire   [0:0] grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_WID;
wire   [0:0] grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_WUSER;
wire    grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_ARVALID;
wire   [31:0] grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_ARADDR;
wire   [0:0] grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_ARID;
wire   [31:0] grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_ARLEN;
wire   [2:0] grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_ARSIZE;
wire   [1:0] grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_ARBURST;
wire   [1:0] grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_ARLOCK;
wire   [3:0] grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_ARCACHE;
wire   [2:0] grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_ARPROT;
wire   [3:0] grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_ARQOS;
wire   [3:0] grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_ARREGION;
wire   [0:0] grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_ARUSER;
wire    grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_RREADY;
wire    grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_BREADY;
wire    grp_generatepartitions0_fu_124_m_axi_kvstats_AWVALID;
wire   [31:0] grp_generatepartitions0_fu_124_m_axi_kvstats_AWADDR;
wire   [0:0] grp_generatepartitions0_fu_124_m_axi_kvstats_AWID;
wire   [31:0] grp_generatepartitions0_fu_124_m_axi_kvstats_AWLEN;
wire   [2:0] grp_generatepartitions0_fu_124_m_axi_kvstats_AWSIZE;
wire   [1:0] grp_generatepartitions0_fu_124_m_axi_kvstats_AWBURST;
wire   [1:0] grp_generatepartitions0_fu_124_m_axi_kvstats_AWLOCK;
wire   [3:0] grp_generatepartitions0_fu_124_m_axi_kvstats_AWCACHE;
wire   [2:0] grp_generatepartitions0_fu_124_m_axi_kvstats_AWPROT;
wire   [3:0] grp_generatepartitions0_fu_124_m_axi_kvstats_AWQOS;
wire   [3:0] grp_generatepartitions0_fu_124_m_axi_kvstats_AWREGION;
wire   [0:0] grp_generatepartitions0_fu_124_m_axi_kvstats_AWUSER;
wire    grp_generatepartitions0_fu_124_m_axi_kvstats_WVALID;
wire   [63:0] grp_generatepartitions0_fu_124_m_axi_kvstats_WDATA;
wire   [7:0] grp_generatepartitions0_fu_124_m_axi_kvstats_WSTRB;
wire    grp_generatepartitions0_fu_124_m_axi_kvstats_WLAST;
wire   [0:0] grp_generatepartitions0_fu_124_m_axi_kvstats_WID;
wire   [0:0] grp_generatepartitions0_fu_124_m_axi_kvstats_WUSER;
wire    grp_generatepartitions0_fu_124_m_axi_kvstats_ARVALID;
wire   [31:0] grp_generatepartitions0_fu_124_m_axi_kvstats_ARADDR;
wire   [0:0] grp_generatepartitions0_fu_124_m_axi_kvstats_ARID;
wire   [31:0] grp_generatepartitions0_fu_124_m_axi_kvstats_ARLEN;
wire   [2:0] grp_generatepartitions0_fu_124_m_axi_kvstats_ARSIZE;
wire   [1:0] grp_generatepartitions0_fu_124_m_axi_kvstats_ARBURST;
wire   [1:0] grp_generatepartitions0_fu_124_m_axi_kvstats_ARLOCK;
wire   [3:0] grp_generatepartitions0_fu_124_m_axi_kvstats_ARCACHE;
wire   [2:0] grp_generatepartitions0_fu_124_m_axi_kvstats_ARPROT;
wire   [3:0] grp_generatepartitions0_fu_124_m_axi_kvstats_ARQOS;
wire   [3:0] grp_generatepartitions0_fu_124_m_axi_kvstats_ARREGION;
wire   [0:0] grp_generatepartitions0_fu_124_m_axi_kvstats_ARUSER;
wire    grp_generatepartitions0_fu_124_m_axi_kvstats_RREADY;
wire    grp_generatepartitions0_fu_124_m_axi_kvstats_BREADY;
reg    grp_generatepartitions0_fu_124_ap_start_reg;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state14;
wire   [63:0] zext_ln1547_fu_168_p1;
wire   [63:0] zext_ln1548_fu_183_p1;
wire   [63:0] zext_ln1550_fu_198_p1;
wire   [63:0] zext_ln1551_fu_213_p1;
reg   [13:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 14'd1;
#0 grp_generatepartitions0_fu_124_ap_start_reg = 1'b0;
end

topkernel_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
topkernel_control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle),
    .kvsetdramA_V(kvsetdramA_V),
    .kvdramA(kvdramA)
);

topkernel_gmem0_m_axi #(
    .CONSERVATIVE( 0 ),
    .USER_DW( 512 ),
    .USER_AW( 32 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 64 ),
    .MAX_WRITE_BURST_LENGTH( 64 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM0_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM0_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM0_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM0_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM0_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM0_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM0_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM0_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM0_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM0_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM0_CACHE_VALUE ))
topkernel_gmem0_m_axi_U(
    .AWVALID(m_axi_gmem0_AWVALID),
    .AWREADY(m_axi_gmem0_AWREADY),
    .AWADDR(m_axi_gmem0_AWADDR),
    .AWID(m_axi_gmem0_AWID),
    .AWLEN(m_axi_gmem0_AWLEN),
    .AWSIZE(m_axi_gmem0_AWSIZE),
    .AWBURST(m_axi_gmem0_AWBURST),
    .AWLOCK(m_axi_gmem0_AWLOCK),
    .AWCACHE(m_axi_gmem0_AWCACHE),
    .AWPROT(m_axi_gmem0_AWPROT),
    .AWQOS(m_axi_gmem0_AWQOS),
    .AWREGION(m_axi_gmem0_AWREGION),
    .AWUSER(m_axi_gmem0_AWUSER),
    .WVALID(m_axi_gmem0_WVALID),
    .WREADY(m_axi_gmem0_WREADY),
    .WDATA(m_axi_gmem0_WDATA),
    .WSTRB(m_axi_gmem0_WSTRB),
    .WLAST(m_axi_gmem0_WLAST),
    .WID(m_axi_gmem0_WID),
    .WUSER(m_axi_gmem0_WUSER),
    .ARVALID(m_axi_gmem0_ARVALID),
    .ARREADY(m_axi_gmem0_ARREADY),
    .ARADDR(m_axi_gmem0_ARADDR),
    .ARID(m_axi_gmem0_ARID),
    .ARLEN(m_axi_gmem0_ARLEN),
    .ARSIZE(m_axi_gmem0_ARSIZE),
    .ARBURST(m_axi_gmem0_ARBURST),
    .ARLOCK(m_axi_gmem0_ARLOCK),
    .ARCACHE(m_axi_gmem0_ARCACHE),
    .ARPROT(m_axi_gmem0_ARPROT),
    .ARQOS(m_axi_gmem0_ARQOS),
    .ARREGION(m_axi_gmem0_ARREGION),
    .ARUSER(m_axi_gmem0_ARUSER),
    .RVALID(m_axi_gmem0_RVALID),
    .RREADY(m_axi_gmem0_RREADY),
    .RDATA(m_axi_gmem0_RDATA),
    .RLAST(m_axi_gmem0_RLAST),
    .RID(m_axi_gmem0_RID),
    .RUSER(m_axi_gmem0_RUSER),
    .RRESP(m_axi_gmem0_RRESP),
    .BVALID(m_axi_gmem0_BVALID),
    .BREADY(m_axi_gmem0_BREADY),
    .BRESP(m_axi_gmem0_BRESP),
    .BID(m_axi_gmem0_BID),
    .BUSER(m_axi_gmem0_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(gmem0_ARVALID),
    .I_ARREADY(gmem0_ARREADY),
    .I_ARADDR(grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_ARADDR),
    .I_ARID(grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_ARID),
    .I_ARLEN(grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_ARLEN),
    .I_ARSIZE(grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_ARSIZE),
    .I_ARLOCK(grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_ARLOCK),
    .I_ARCACHE(grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_ARCACHE),
    .I_ARQOS(grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_ARQOS),
    .I_ARPROT(grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_ARPROT),
    .I_ARUSER(grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_ARUSER),
    .I_ARBURST(grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_ARBURST),
    .I_ARREGION(grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_ARREGION),
    .I_RVALID(gmem0_RVALID),
    .I_RREADY(gmem0_RREADY),
    .I_RDATA(gmem0_RDATA),
    .I_RID(gmem0_RID),
    .I_RUSER(gmem0_RUSER),
    .I_RRESP(gmem0_RRESP),
    .I_RLAST(gmem0_RLAST),
    .I_AWVALID(gmem0_AWVALID),
    .I_AWREADY(gmem0_AWREADY),
    .I_AWADDR(grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_AWADDR),
    .I_AWID(grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_AWID),
    .I_AWLEN(grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_AWLEN),
    .I_AWSIZE(grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_AWSIZE),
    .I_AWLOCK(grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_AWLOCK),
    .I_AWCACHE(grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_AWCACHE),
    .I_AWQOS(grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_AWQOS),
    .I_AWPROT(grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_AWPROT),
    .I_AWUSER(grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_AWUSER),
    .I_AWBURST(grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_AWBURST),
    .I_AWREGION(grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_AWREGION),
    .I_WVALID(gmem0_WVALID),
    .I_WREADY(gmem0_WREADY),
    .I_WDATA(grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_WDATA),
    .I_WID(grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_WID),
    .I_WUSER(grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_WUSER),
    .I_WLAST(grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_WLAST),
    .I_WSTRB(grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_WSTRB),
    .I_BVALID(gmem0_BVALID),
    .I_BREADY(gmem0_BREADY),
    .I_BRESP(gmem0_BRESP),
    .I_BID(gmem0_BID),
    .I_BUSER(gmem0_BUSER)
);

topkernel_gmem1_m_axi #(
    .CONSERVATIVE( 0 ),
    .USER_DW( 64 ),
    .USER_AW( 32 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM1_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM1_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM1_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM1_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM1_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM1_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM1_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM1_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM1_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM1_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM1_CACHE_VALUE ))
topkernel_gmem1_m_axi_U(
    .AWVALID(m_axi_gmem1_AWVALID),
    .AWREADY(m_axi_gmem1_AWREADY),
    .AWADDR(m_axi_gmem1_AWADDR),
    .AWID(m_axi_gmem1_AWID),
    .AWLEN(m_axi_gmem1_AWLEN),
    .AWSIZE(m_axi_gmem1_AWSIZE),
    .AWBURST(m_axi_gmem1_AWBURST),
    .AWLOCK(m_axi_gmem1_AWLOCK),
    .AWCACHE(m_axi_gmem1_AWCACHE),
    .AWPROT(m_axi_gmem1_AWPROT),
    .AWQOS(m_axi_gmem1_AWQOS),
    .AWREGION(m_axi_gmem1_AWREGION),
    .AWUSER(m_axi_gmem1_AWUSER),
    .WVALID(m_axi_gmem1_WVALID),
    .WREADY(m_axi_gmem1_WREADY),
    .WDATA(m_axi_gmem1_WDATA),
    .WSTRB(m_axi_gmem1_WSTRB),
    .WLAST(m_axi_gmem1_WLAST),
    .WID(m_axi_gmem1_WID),
    .WUSER(m_axi_gmem1_WUSER),
    .ARVALID(m_axi_gmem1_ARVALID),
    .ARREADY(m_axi_gmem1_ARREADY),
    .ARADDR(m_axi_gmem1_ARADDR),
    .ARID(m_axi_gmem1_ARID),
    .ARLEN(m_axi_gmem1_ARLEN),
    .ARSIZE(m_axi_gmem1_ARSIZE),
    .ARBURST(m_axi_gmem1_ARBURST),
    .ARLOCK(m_axi_gmem1_ARLOCK),
    .ARCACHE(m_axi_gmem1_ARCACHE),
    .ARPROT(m_axi_gmem1_ARPROT),
    .ARQOS(m_axi_gmem1_ARQOS),
    .ARREGION(m_axi_gmem1_ARREGION),
    .ARUSER(m_axi_gmem1_ARUSER),
    .RVALID(m_axi_gmem1_RVALID),
    .RREADY(m_axi_gmem1_RREADY),
    .RDATA(m_axi_gmem1_RDATA),
    .RLAST(m_axi_gmem1_RLAST),
    .RID(m_axi_gmem1_RID),
    .RUSER(m_axi_gmem1_RUSER),
    .RRESP(m_axi_gmem1_RRESP),
    .BVALID(m_axi_gmem1_BVALID),
    .BREADY(m_axi_gmem1_BREADY),
    .BRESP(m_axi_gmem1_BRESP),
    .BID(m_axi_gmem1_BID),
    .BUSER(m_axi_gmem1_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(gmem1_ARVALID),
    .I_ARREADY(gmem1_ARREADY),
    .I_ARADDR(gmem1_ARADDR),
    .I_ARID(gmem1_ARID),
    .I_ARLEN(gmem1_ARLEN),
    .I_ARSIZE(gmem1_ARSIZE),
    .I_ARLOCK(gmem1_ARLOCK),
    .I_ARCACHE(gmem1_ARCACHE),
    .I_ARQOS(gmem1_ARQOS),
    .I_ARPROT(gmem1_ARPROT),
    .I_ARUSER(gmem1_ARUSER),
    .I_ARBURST(gmem1_ARBURST),
    .I_ARREGION(gmem1_ARREGION),
    .I_RVALID(gmem1_RVALID),
    .I_RREADY(gmem1_RREADY),
    .I_RDATA(gmem1_RDATA),
    .I_RID(gmem1_RID),
    .I_RUSER(gmem1_RUSER),
    .I_RRESP(gmem1_RRESP),
    .I_RLAST(gmem1_RLAST),
    .I_AWVALID(gmem1_AWVALID),
    .I_AWREADY(gmem1_AWREADY),
    .I_AWADDR(grp_generatepartitions0_fu_124_m_axi_kvstats_AWADDR),
    .I_AWID(grp_generatepartitions0_fu_124_m_axi_kvstats_AWID),
    .I_AWLEN(grp_generatepartitions0_fu_124_m_axi_kvstats_AWLEN),
    .I_AWSIZE(grp_generatepartitions0_fu_124_m_axi_kvstats_AWSIZE),
    .I_AWLOCK(grp_generatepartitions0_fu_124_m_axi_kvstats_AWLOCK),
    .I_AWCACHE(grp_generatepartitions0_fu_124_m_axi_kvstats_AWCACHE),
    .I_AWQOS(grp_generatepartitions0_fu_124_m_axi_kvstats_AWQOS),
    .I_AWPROT(grp_generatepartitions0_fu_124_m_axi_kvstats_AWPROT),
    .I_AWUSER(grp_generatepartitions0_fu_124_m_axi_kvstats_AWUSER),
    .I_AWBURST(grp_generatepartitions0_fu_124_m_axi_kvstats_AWBURST),
    .I_AWREGION(grp_generatepartitions0_fu_124_m_axi_kvstats_AWREGION),
    .I_WVALID(gmem1_WVALID),
    .I_WREADY(gmem1_WREADY),
    .I_WDATA(grp_generatepartitions0_fu_124_m_axi_kvstats_WDATA),
    .I_WID(grp_generatepartitions0_fu_124_m_axi_kvstats_WID),
    .I_WUSER(grp_generatepartitions0_fu_124_m_axi_kvstats_WUSER),
    .I_WLAST(grp_generatepartitions0_fu_124_m_axi_kvstats_WLAST),
    .I_WSTRB(grp_generatepartitions0_fu_124_m_axi_kvstats_WSTRB),
    .I_BVALID(gmem1_BVALID),
    .I_BREADY(gmem1_BREADY),
    .I_BRESP(gmem1_BRESP),
    .I_BID(gmem1_BID),
    .I_BUSER(gmem1_BUSER)
);

generatepartitions0 grp_generatepartitions0_fu_124(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_generatepartitions0_fu_124_ap_start),
    .ap_done(grp_generatepartitions0_fu_124_ap_done),
    .ap_idle(grp_generatepartitions0_fu_124_ap_idle),
    .ap_ready(grp_generatepartitions0_fu_124_ap_ready),
    .m_axi_kvsetdram_V_AWVALID(grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_AWVALID),
    .m_axi_kvsetdram_V_AWREADY(gmem0_AWREADY),
    .m_axi_kvsetdram_V_AWADDR(grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_AWADDR),
    .m_axi_kvsetdram_V_AWID(grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_AWID),
    .m_axi_kvsetdram_V_AWLEN(grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_AWLEN),
    .m_axi_kvsetdram_V_AWSIZE(grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_AWSIZE),
    .m_axi_kvsetdram_V_AWBURST(grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_AWBURST),
    .m_axi_kvsetdram_V_AWLOCK(grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_AWLOCK),
    .m_axi_kvsetdram_V_AWCACHE(grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_AWCACHE),
    .m_axi_kvsetdram_V_AWPROT(grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_AWPROT),
    .m_axi_kvsetdram_V_AWQOS(grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_AWQOS),
    .m_axi_kvsetdram_V_AWREGION(grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_AWREGION),
    .m_axi_kvsetdram_V_AWUSER(grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_AWUSER),
    .m_axi_kvsetdram_V_WVALID(grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_WVALID),
    .m_axi_kvsetdram_V_WREADY(gmem0_WREADY),
    .m_axi_kvsetdram_V_WDATA(grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_WDATA),
    .m_axi_kvsetdram_V_WSTRB(grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_WSTRB),
    .m_axi_kvsetdram_V_WLAST(grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_WLAST),
    .m_axi_kvsetdram_V_WID(grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_WID),
    .m_axi_kvsetdram_V_WUSER(grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_WUSER),
    .m_axi_kvsetdram_V_ARVALID(grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_ARVALID),
    .m_axi_kvsetdram_V_ARREADY(gmem0_ARREADY),
    .m_axi_kvsetdram_V_ARADDR(grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_ARADDR),
    .m_axi_kvsetdram_V_ARID(grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_ARID),
    .m_axi_kvsetdram_V_ARLEN(grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_ARLEN),
    .m_axi_kvsetdram_V_ARSIZE(grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_ARSIZE),
    .m_axi_kvsetdram_V_ARBURST(grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_ARBURST),
    .m_axi_kvsetdram_V_ARLOCK(grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_ARLOCK),
    .m_axi_kvsetdram_V_ARCACHE(grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_ARCACHE),
    .m_axi_kvsetdram_V_ARPROT(grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_ARPROT),
    .m_axi_kvsetdram_V_ARQOS(grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_ARQOS),
    .m_axi_kvsetdram_V_ARREGION(grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_ARREGION),
    .m_axi_kvsetdram_V_ARUSER(grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_ARUSER),
    .m_axi_kvsetdram_V_RVALID(gmem0_RVALID),
    .m_axi_kvsetdram_V_RREADY(grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_RREADY),
    .m_axi_kvsetdram_V_RDATA(gmem0_RDATA),
    .m_axi_kvsetdram_V_RLAST(gmem0_RLAST),
    .m_axi_kvsetdram_V_RID(gmem0_RID),
    .m_axi_kvsetdram_V_RUSER(gmem0_RUSER),
    .m_axi_kvsetdram_V_RRESP(gmem0_RRESP),
    .m_axi_kvsetdram_V_BVALID(gmem0_BVALID),
    .m_axi_kvsetdram_V_BREADY(grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_BREADY),
    .m_axi_kvsetdram_V_BRESP(gmem0_BRESP),
    .m_axi_kvsetdram_V_BID(gmem0_BID),
    .m_axi_kvsetdram_V_BUSER(gmem0_BUSER),
    .kvsetdram_V_offset(kvsetdramA_V1_reg_251),
    .m_axi_kvstats_AWVALID(grp_generatepartitions0_fu_124_m_axi_kvstats_AWVALID),
    .m_axi_kvstats_AWREADY(gmem1_AWREADY),
    .m_axi_kvstats_AWADDR(grp_generatepartitions0_fu_124_m_axi_kvstats_AWADDR),
    .m_axi_kvstats_AWID(grp_generatepartitions0_fu_124_m_axi_kvstats_AWID),
    .m_axi_kvstats_AWLEN(grp_generatepartitions0_fu_124_m_axi_kvstats_AWLEN),
    .m_axi_kvstats_AWSIZE(grp_generatepartitions0_fu_124_m_axi_kvstats_AWSIZE),
    .m_axi_kvstats_AWBURST(grp_generatepartitions0_fu_124_m_axi_kvstats_AWBURST),
    .m_axi_kvstats_AWLOCK(grp_generatepartitions0_fu_124_m_axi_kvstats_AWLOCK),
    .m_axi_kvstats_AWCACHE(grp_generatepartitions0_fu_124_m_axi_kvstats_AWCACHE),
    .m_axi_kvstats_AWPROT(grp_generatepartitions0_fu_124_m_axi_kvstats_AWPROT),
    .m_axi_kvstats_AWQOS(grp_generatepartitions0_fu_124_m_axi_kvstats_AWQOS),
    .m_axi_kvstats_AWREGION(grp_generatepartitions0_fu_124_m_axi_kvstats_AWREGION),
    .m_axi_kvstats_AWUSER(grp_generatepartitions0_fu_124_m_axi_kvstats_AWUSER),
    .m_axi_kvstats_WVALID(grp_generatepartitions0_fu_124_m_axi_kvstats_WVALID),
    .m_axi_kvstats_WREADY(gmem1_WREADY),
    .m_axi_kvstats_WDATA(grp_generatepartitions0_fu_124_m_axi_kvstats_WDATA),
    .m_axi_kvstats_WSTRB(grp_generatepartitions0_fu_124_m_axi_kvstats_WSTRB),
    .m_axi_kvstats_WLAST(grp_generatepartitions0_fu_124_m_axi_kvstats_WLAST),
    .m_axi_kvstats_WID(grp_generatepartitions0_fu_124_m_axi_kvstats_WID),
    .m_axi_kvstats_WUSER(grp_generatepartitions0_fu_124_m_axi_kvstats_WUSER),
    .m_axi_kvstats_ARVALID(grp_generatepartitions0_fu_124_m_axi_kvstats_ARVALID),
    .m_axi_kvstats_ARREADY(gmem1_ARREADY),
    .m_axi_kvstats_ARADDR(grp_generatepartitions0_fu_124_m_axi_kvstats_ARADDR),
    .m_axi_kvstats_ARID(grp_generatepartitions0_fu_124_m_axi_kvstats_ARID),
    .m_axi_kvstats_ARLEN(grp_generatepartitions0_fu_124_m_axi_kvstats_ARLEN),
    .m_axi_kvstats_ARSIZE(grp_generatepartitions0_fu_124_m_axi_kvstats_ARSIZE),
    .m_axi_kvstats_ARBURST(grp_generatepartitions0_fu_124_m_axi_kvstats_ARBURST),
    .m_axi_kvstats_ARLOCK(grp_generatepartitions0_fu_124_m_axi_kvstats_ARLOCK),
    .m_axi_kvstats_ARCACHE(grp_generatepartitions0_fu_124_m_axi_kvstats_ARCACHE),
    .m_axi_kvstats_ARPROT(grp_generatepartitions0_fu_124_m_axi_kvstats_ARPROT),
    .m_axi_kvstats_ARQOS(grp_generatepartitions0_fu_124_m_axi_kvstats_ARQOS),
    .m_axi_kvstats_ARREGION(grp_generatepartitions0_fu_124_m_axi_kvstats_ARREGION),
    .m_axi_kvstats_ARUSER(grp_generatepartitions0_fu_124_m_axi_kvstats_ARUSER),
    .m_axi_kvstats_RVALID(gmem1_RVALID),
    .m_axi_kvstats_RREADY(grp_generatepartitions0_fu_124_m_axi_kvstats_RREADY),
    .m_axi_kvstats_RDATA(gmem1_RDATA),
    .m_axi_kvstats_RLAST(gmem1_RLAST),
    .m_axi_kvstats_RID(gmem1_RID),
    .m_axi_kvstats_RUSER(gmem1_RUSER),
    .m_axi_kvstats_RRESP(gmem1_RRESP),
    .m_axi_kvstats_BVALID(gmem1_BVALID),
    .m_axi_kvstats_BREADY(grp_generatepartitions0_fu_124_m_axi_kvstats_BREADY),
    .m_axi_kvstats_BRESP(gmem1_BRESP),
    .m_axi_kvstats_BID(gmem1_BID),
    .m_axi_kvstats_BUSER(gmem1_BUSER),
    .kvstats_offset(kvdramA3_reg_239),
    .globalparams_reducecommand(globalparams_reducec_reg_300),
    .globalparams_treedepth(globalparams_treedep_reg_310),
    .globalparams_LLOPnumpartitions(globalparams_LLOPnum_reg_315),
    .globalparams_vbegin(globalparams_vbegin_reg_305)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_generatepartitions0_fu_124_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state13)) begin
            grp_generatepartitions0_fu_124_ap_start_reg <= 1'b1;
        end else if ((grp_generatepartitions0_fu_124_ap_ready == 1'b1)) begin
            grp_generatepartitions0_fu_124_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        add_ln1547_reg_256 <= add_ln1547_fu_162_p2;
        kvdramA3_reg_239 <= {{kvdramA[31:3]}};
        kvsetdramA_V1_reg_251 <= {{kvsetdramA_V[31:6]}};
        p_cast_reg_244[28 : 0] <= p_cast_fu_148_p1[28 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((gmem1_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        add_ln1548_reg_267 <= add_ln1548_fu_178_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((gmem1_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        add_ln1550_reg_278 <= add_ln1550_fu_193_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((gmem1_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        add_ln1551_reg_289 <= add_ln1551_fu_208_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((gmem1_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
        globalparams_LLOPnum_reg_315 <= globalparams_LLOPnum_fu_235_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((gmem1_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        globalparams_reducec_reg_300 <= globalparams_reducec_fu_223_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((gmem1_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        globalparams_treedep_reg_310 <= globalparams_treedep_fu_231_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((gmem1_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        globalparams_vbegin_reg_305 <= globalparams_vbegin_fu_227_p1;
    end
end

always @ (*) begin
    if (((grp_generatepartitions0_fu_124_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_generatepartitions0_fu_124_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        gmem0_ARVALID = grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_ARVALID;
    end else begin
        gmem0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        gmem0_AWVALID = grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_AWVALID;
    end else begin
        gmem0_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        gmem0_BREADY = grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_BREADY;
    end else begin
        gmem0_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        gmem0_RREADY = grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_RREADY;
    end else begin
        gmem0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        gmem0_WVALID = grp_generatepartitions0_fu_124_m_axi_kvsetdram_V_WVALID;
    end else begin
        gmem0_WVALID = 1'b0;
    end
end

always @ (*) begin
    if (((gmem1_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        gmem1_ARADDR = zext_ln1551_fu_213_p1;
    end else if (((gmem1_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        gmem1_ARADDR = zext_ln1550_fu_198_p1;
    end else if (((gmem1_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        gmem1_ARADDR = zext_ln1548_fu_183_p1;
    end else if (((gmem1_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        gmem1_ARADDR = zext_ln1547_fu_168_p1;
    end else if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        gmem1_ARADDR = grp_generatepartitions0_fu_124_m_axi_kvstats_ARADDR;
    end else begin
        gmem1_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        gmem1_ARBURST = grp_generatepartitions0_fu_124_m_axi_kvstats_ARBURST;
    end else begin
        gmem1_ARBURST = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        gmem1_ARCACHE = grp_generatepartitions0_fu_124_m_axi_kvstats_ARCACHE;
    end else begin
        gmem1_ARCACHE = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        gmem1_ARID = grp_generatepartitions0_fu_124_m_axi_kvstats_ARID;
    end else begin
        gmem1_ARID = 1'd0;
    end
end

always @ (*) begin
    if ((((gmem1_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((gmem1_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state4)) | ((gmem1_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state3)) | ((gmem1_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2)))) begin
        gmem1_ARLEN = 32'd1;
    end else if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        gmem1_ARLEN = grp_generatepartitions0_fu_124_m_axi_kvstats_ARLEN;
    end else begin
        gmem1_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        gmem1_ARLOCK = grp_generatepartitions0_fu_124_m_axi_kvstats_ARLOCK;
    end else begin
        gmem1_ARLOCK = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        gmem1_ARPROT = grp_generatepartitions0_fu_124_m_axi_kvstats_ARPROT;
    end else begin
        gmem1_ARPROT = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        gmem1_ARQOS = grp_generatepartitions0_fu_124_m_axi_kvstats_ARQOS;
    end else begin
        gmem1_ARQOS = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        gmem1_ARREGION = grp_generatepartitions0_fu_124_m_axi_kvstats_ARREGION;
    end else begin
        gmem1_ARREGION = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        gmem1_ARSIZE = grp_generatepartitions0_fu_124_m_axi_kvstats_ARSIZE;
    end else begin
        gmem1_ARSIZE = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        gmem1_ARUSER = grp_generatepartitions0_fu_124_m_axi_kvstats_ARUSER;
    end else begin
        gmem1_ARUSER = 1'd0;
    end
end

always @ (*) begin
    if ((((gmem1_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((gmem1_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state4)) | ((gmem1_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state3)) | ((gmem1_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2)))) begin
        gmem1_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        gmem1_ARVALID = grp_generatepartitions0_fu_124_m_axi_kvstats_ARVALID;
    end else begin
        gmem1_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        gmem1_AWVALID = grp_generatepartitions0_fu_124_m_axi_kvstats_AWVALID;
    end else begin
        gmem1_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        gmem1_BREADY = grp_generatepartitions0_fu_124_m_axi_kvstats_BREADY;
    end else begin
        gmem1_BREADY = 1'b0;
    end
end

always @ (*) begin
    if ((((gmem1_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state12)) | ((gmem1_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state11)) | ((gmem1_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state10)) | ((gmem1_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state9)))) begin
        gmem1_RREADY = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        gmem1_RREADY = grp_generatepartitions0_fu_124_m_axi_kvstats_RREADY;
    end else begin
        gmem1_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        gmem1_WVALID = grp_generatepartitions0_fu_124_m_axi_kvstats_WVALID;
    end else begin
        gmem1_WVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        gmem1_blk_n_AR = m_axi_gmem1_ARREADY;
    end else begin
        gmem1_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        gmem1_blk_n_R = m_axi_gmem1_RVALID;
    end else begin
        gmem1_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((gmem1_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((gmem1_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((gmem1_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((gmem1_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((gmem1_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            if (((gmem1_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            if (((gmem1_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            if (((gmem1_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            if (((grp_generatepartitions0_fu_124_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1547_fu_162_p2 = (30'd32771 + p_cast_fu_148_p1);

assign add_ln1548_fu_178_p2 = (30'd32777 + p_cast_reg_244);

assign add_ln1550_fu_193_p2 = (30'd32779 + p_cast_reg_244);

assign add_ln1551_fu_208_p2 = (30'd32780 + p_cast_reg_244);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign globalparams_LLOPnum_fu_235_p1 = gmem1_RDATA[31:0];

assign globalparams_reducec_fu_223_p1 = gmem1_RDATA[31:0];

assign globalparams_treedep_fu_231_p1 = gmem1_RDATA[31:0];

assign globalparams_vbegin_fu_227_p1 = gmem1_RDATA[31:0];

assign grp_generatepartitions0_fu_124_ap_start = grp_generatepartitions0_fu_124_ap_start_reg;

assign kvdramA3_fu_138_p4 = {{kvdramA[31:3]}};

assign p_cast_fu_148_p1 = kvdramA3_fu_138_p4;

assign zext_ln1547_fu_168_p1 = add_ln1547_reg_256;

assign zext_ln1548_fu_183_p1 = add_ln1548_reg_267;

assign zext_ln1550_fu_198_p1 = add_ln1550_reg_278;

assign zext_ln1551_fu_213_p1 = add_ln1551_reg_289;

always @ (posedge ap_clk) begin
    p_cast_reg_244[29] <= 1'b0;
end

endmodule //topkernel
